### PR TITLE
feat(Grid): add `container` prop

### PR DESCRIPTION
**Pull request by tarang9211**
Is this what we were going for?

### CODE REVIEW

**Comment by tarang9211** [comment]
@levithomason does that look alright to you? do we need docs for this feature too?

**Comment by levithomason** [comment]
Yep!  Now, we just need an example.  Our examples mirror SUI core examples.  Here is the core grid container example: http://semantic-ui.com/collections/grid#containers

You can reference our Grid examples in `docs/app/Examples/collections/Grid`.  The `container` example would go into the [Responsive Variations](http://react.semantic-ui.com/collections/grid#responsive-variations) section.

**Comment by tarang9211** [comment]
I'm on this @levithomason

**Comment by tarang9211** [comment]
@levithomason added the example to the docs site. let me know if this is good.

**Comment by levithomason** [comment]
Great. I made one update in the last commit, 8af2a62.  Prop strings cannot be multi-line.  Looks good otherwise, I'll merge this on pass.

**Comment by tarang9211** [comment]
oh ok, sorry about that. the reason I did that was because eslint threw an error. Didn't know we could methods on react props.

**Comment by levithomason** [comment]
No worries!  Figured I show the concatenation trick while at it.  FWIW:

Backticks (`` ` ``) preserve whitespace, including newlines:

```js
const multiline = `Line 1
Line2
Line2`
```

But regular quotes (`'` and `"`) do not:

```jsx
const error = 'line 1
line 2'
//=> Uncaught SyntaxError: Invalid or unexpected token
```

A nice trick is to use `[].join()` to join multiple lines.  This is not only far faster than string concatenation, but it also allows better indenting without adding lots of whitespace in the string:

```jsx
const nice = [
  'line 1',
  'line 2',
  'line 3',
].join('\n')
```

To create a single line string, just `join('')` instead 👍

**Comment by tarang9211** [comment]
Awesome, thanks for that tip!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.63.3`.

**Pull request merged**
