### PR TITLE
fix(typings): make TableHeaderCell `sorted` optional

### PR DESCRIPTION
**Pull request by squirly**

### CODE REVIEW

**Review by layershifter — APPROVED** [review]

**Comment by layershifter** [comment]
@squirly Thanks for PR

**Comment by squirly** [comment]
The CircleCI build did not report back. I probably needs to be rebuilt. They did have some degradation earlier today at the same time this build ran.

**Comment by levithomason** [comment]
Thanks, appears to have [passed](https://circleci.com/gh/Semantic-Org/Semantic-UI-React/1743?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) :)

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.64.5`.

**Pull request merged**
