### PR TITLE
style(typings): add new types

### LINKED ISSUE #1289: RFC: New types for typings
We have `customPropTypes` for our shorthands and it works fine :smile: But, their represent in typings is not obvious.

My suggestion is to add new types for `customPropTypes` and update existing typings:

```ts
type ShorthandCollection = Array<ShorthandItem>; // for customPropTypes.collectionShorthand
type ShorthandContent = React.ReactNode; // for customPropTypes.contentShorthand
type ShorthandItem = any; // for customPropTypes.itemShorthand
```

@levithomason any feedback?

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1289.

This PR:
- add new types for typings as described in #1289;
- add new tests that check that all types are same as in `propTypes`.

### CODE REVIEW

**Comment by layershifter** [comment]
@levithomason we have following validator:

```jsx
export const itemShorthand = (...args) => every([
  disallow(['children']),
  PropTypes.oneOfType([
    PropTypes.array,
    PropTypes.node,
    PropTypes.object,
  ]),
])(...args)
```
However, I don't remember any case when `itemShorthand` can be an array. Can you clarify?

**Review by layershifter — COMMENTED** [review]
@levithomason Ready for review, also please pay attention to the question above.

**Comment by levithomason** [comment]
>However, I don't remember any case when itemShorthand can be an array. Can you clarify?

I went back and checked some old issues and discussions around this.  I think we can remove the array type from `itemShorthand` now.  Give it a go and see if you run into any test failures or documentation issues and we'll go from there.

**Comment by layershifter** [comment]
@levithomason you have already [removed](https://github.com/Semantic-Org/Semantic-UI-React/commit/afb911028b7aa3075a9ecb5b8bee5349f7fdb191#diff-e69b41f3944b4607ec8c9e9218a6eb4eL285) it in the `Tab`'s PR 😄 So, we're ready for review there.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.1`.

**Pull request merged**
