### PR TITLE
feat(Sticky|Visibility): listen for `resize` events

### PR DESCRIPTION
**Pull request by layershifter**
Cut from #2088.

# What?

`Sticky` and `Visibility` should also listen for `resize` events as SUI component does.

- [`Sticky`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/sticky.js#L209)
- [`Visibility`](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/behaviors/visibility.js#L201)

### CODE REVIEW

**Comment by levithomason** [comment]
Minor conflict to address here.

**Comment by levithomason** [comment]
Fixed conflict, good to merge after tests pass and you confirm the conflict fix is correct.

**Comment by layershifter** [comment]
@levithomason I will fix it now

**Comment by layershifter** [comment]
Fixed, waiting for CI pass

**Comment by layershifter** [comment]
@levithomason As you approved these changes, I merged them

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.74.0`

**Pull request merged**
