### PR TITLE
BREAKING(package): update to React 16

### LINKED ISSUE #2747: Update to React 16
React 16 offers some updates that we should implement, however, we'll need to drop support for React 15 when doing so.  Let's batch these changes into an upcoming major release:

- [x] #2746 Portal to use `ReactDOM.createPortal` (https://reactjs.org/docs/portals.html)
- [ ] Refactor and simplify Accordion to return an array of panels (https://reactjs.org/docs/react-component.html#render)
- [ ] Refactor and simplify Breadcrumb to return an array of sections/dividers (https://reactjs.org/docs/react-component.html#render)
- [ ] #2306 Fix ref issues using `forwardRef` (https://reactjs.org/docs/forwarding-refs.html)
- [x] #2842 Use `PureComponent` for `Icon` and `Flag`

@Semantic-Org/react-maintainers feel free to add to this list at will...

### LINKED ISSUE #2886: Portal: recent change breaks in IE11
## Bug Report

A change introduced in #2657 to the portal component causes an error in IE11 when trying to open anything using a portal.

The change: 
https://github.com/Semantic-Org/Semantic-UI-React/blob/500df9ae073dc99b3425fda89fe6b3a3d8f56760/src/addons/Portal/Portal.js#L355

### Steps
Use anything with a portal in IE11 and try to open it.

### Expected Result
Should open the portal.

### Actual Result
Throws the following error:
```
SCRIPT5045: Assignment to read-only properties is not allowed in strict mode
```
Which points to the changed line.

### Version
`semantic-ui-react@0.81.1`

### LINKED ISSUE #2910: <Portal/> and new context API
### Steps
Just try to use new context API.
The problem is caused by using `unstable_renderSubtreeIntoContainer` function (facebook/react#12493).

### Expected Result
Access to context value.

### Actual Result
Context value is `undefined`.

### Version
0.81.1

### Testcase
https://codesandbox.io/s/3r9nkpk1z5

P.S. Can I help with this issue? I have no experience in contributing, but I'd really like to try...

### PR DESCRIPTION
**Pull request by layershifter**
# BREAKING CHANGES

Fixes #2747.
Fixes #2886.
Fixes #2910.

React 16 was released in September 2017, the update process is simple and I don't know any supported application that still uses React 15. It's time to say goodbye to React 15.

Please keep in mind, that in near future we will require React 16.3.

---

### 1. Requirement of React 16

Now SUIR requires `react^16.0.0`.

### 2. Breaking changes in `Portal`

See #2755 for detailed list of performed changes.

### 3. Add the `triggerRef` for `Portal`

See #2902 for more details.

### 4. Breaking changes in the shorthand API of `Accordion`

See #2904 for detailed list of performed changes.

### CODE REVIEW

**Comment by layershifter** [comment]
@levithomason marked as ready for review.

I don't want to include there changes for `Breadcrumb` because they are very unclear. Changes for `forwardRef` I want include to future releases.

**Comment by ivosabev** [comment]
When is this scheduled to ship?

**Comment by layershifter** [comment]
I hope on this or next week.

**Comment by layershifter** [comment]
Merged with masted and solved merge conflicts.

**Comment by levithomason** [comment]
We have two failing tests here, I've run out of time for today:
```
Dropdown
     onOpen
      ✖ is called once when the icon is clicked with a search prop
     search
      ✖ filters the items based on custom search function
  ```

**Comment by mgandley** [comment]
Waiting on this for the IE portal fix!  Thanks for your work on it @layershifter!

**Comment by layershifter** [comment]
> We have two failing tests here, I've run out of time for today:

@levithomason I hate the `Dropdown` component, I will refactor it fully someday

**Comment by layershifter** [comment]
I reverted updates in `yarn.lock`, tests are passed. It seems that we will have the surprise from minor updates in dependencies.

**Comment by layershifter** [comment]
@levithomason I want to merge and release any solution for #2958 before this.

**Comment by levithomason** [comment]
@layershifter I've merged #2958 released `semantic-ui-react@0.81.3`.  I'm good with this PR if and when you are.  Feel free to merge after fixing conflicts and I'll release as `0.82.0`.

**Comment by layershifter** [comment]
Solved merged conflicts and merged :+1:

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.82.0`.

**Pull request merged**
