### PR TITLE
feat(Sidebar): add lifecycle handlers

### PR DESCRIPTION
**Pull request by layershifter**
Requires #2837.
Replaces #2433, #1473.

-----

This PR:
- adds `onHide`, `onHidden`, `onShow` and `onVisible` callbacks to allow the deep control of `visible` prop
- reworks `Sidebar` docs, examples are much better and clear now :+1: 
- improves code coverage

----

Especially thanks to @cjsheets and @mchirkin for their work in previous PRs!

### CODE REVIEW

**Comment by levithomason** [comment]
#2387 merged, unblocked this PR.

**Comment by levithomason** [comment]
Heads up, I've reworked the directories in `/docs`.  This PR needs updated.  There is a detailed upgrade guide in the PR, #2863.

**Comment by layershifter** [comment]
@levithomason marked as ready for review 👍

**Comment by levithomason** [comment]
In http://localhost:8080/modules/sidebar#types-sidebar, clicking outside does not close the Sidebar.  It seems `onHide` is called twice, resulting in a double toggle.

If I create a `handleHide` method that sets visible to false only and assign that to `onHide`, then it works.  However, we should ensure the `onHide` is not called twice.

**Comment by layershifter** [comment]
Will check, sounds stange 🤔

**Comment by layershifter** [comment]
I made some updates, now it works as expected.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.81.2`.

**Pull request merged**
