### PR TITLE
docs(ComponentExample): fix code editor body regex

### PR DESCRIPTION
**Pull request by road-cycling**
Updated to regex to fix error: https://github.com/Semantic-Org/Semantic-UI-React/issues/2465

This is my first pull request, please let me know if I have done anything wrong!

### CODE REVIEW

**Comment by levithomason** [comment]
Cool, be sure to run `yarn test` and `yarn lint`.  Otherwise, you could be waiting for CI to tell you of a lint issue.

**Comment by levithomason** [comment]
tip: On future PRs, you'll want to create a branch in your fork and open the PR from the work on your branch.  This helps isolate multiple threads of work.  It also makes it to where the repo owners can commit back to your branch if need be.  When making a PR from your master branch, this is not possible.

Testing this out now!

**Comment by levithomason** [comment]
The changes fail for the Button example.  There is a mixture of syntax used in examples.  I'd suggest trying your changes in several code files.

http://localhost:8080/elements/button#button-example-button

```jsx
import React from 'react'
import { Button } from 'semantic-ui-react'

const ButtonExampleButton = () => (
  <Button>Click Heres</Button>
)

export default ButtonExampleButton
```

image

**Comment by road-cycling** [comment]
looking through the components I saw that classes are defined in these 3 ways
```javascript
class * extends Component
const * = () => (     
export default class 
```
Sometimes variables were declared above the class, but it would match with the top 'const' (would be an issue if var is used)
```javascript
const data = [foo, bar];
class * extends Component {}
```

This matches all examples above.
```javascript
const body = _.get(/(export\sdefault\sclass|const|class\s\S*\sextends)[\s\S]*/.exec(sourceCode), '[0]', '')
        .replace(/export\s+default\s+(?!class|function)\w+([\s\n]+)?/, '')  // remove `export default Foo` statements
        .replace(/export\s+default\s+/, '')     
```

This assumes the class isnt defined  as such (var * = () => ), and variable definitions above the class is using 'const'

**Comment by levithomason** [comment]
This looks good.  The only issue is that I'm unable to add new lines for some reason.  Pressing enter does not add a new line character.

**Comment by levithomason** [comment]
@nieroda  ^

**Comment by road-cycling** [comment]
I assume you mean the enter key adding a new line? If this is what you mean, I am unable to replicate this on my end as I am having no issues with new lines

**Comment by levithomason** [comment]
OK, I've noticed this on master locally as well.  It could be something with my machine. In either case, it is unrelated to this PR so let's move forward.  Thanks!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.78.3`.

**Pull request merged**
