### PR TITLE
fix(TextArea): fix typings definition

### PR DESCRIPTION
**Pull request by pierre-H**
Fix false definition of TextArea

### CODE REVIEW

**Review by layershifter — APPROVED** [review]
@pierre-H Thanks!

**Comment by thchia** [comment]
Should focus be an optional property?

**Comment by layershifter** [comment]
`focus` isn't React's prop there, it's a class method. So, definition is correct and this will be work:

```tsx
 <TextArea ref={c => c.focus()} />
```

**Comment by thchia** [comment]
Oops you are absolutely right 🙃

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.72.0`

**Pull request merged**
