### PR TITLE
feat(Accordion): ability to open multiple items

### PR DESCRIPTION
**Pull request by levithomason**
Continuation of #976

### CODE REVIEW

**Review by UnbrandedTech — COMMENTED** [review]
Awesome! Thank you for the clean up, I tried to step lightly.

**Comment by levithomason** [comment]
No worries, thanks for the work here.  Looks like I need to add one more test to get the coverage we need.  I've got to switch to other things now so I'll come back here when I get some more time.

**Comment by levithomason** [comment]
This may pass now, thanks to @koenvg writing some more tests.

**Comment by jeffcarbs** [comment]
@levithomason - the build died on circle so I restarted it and looks like it passed. We g2g here?

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.62.2`.

**Pull request merged**
