### PR TITLE
fix(isBrowser): replace OR with AND operator

### PR DESCRIPTION
**Pull request by dcurletti**
#712  SSR fix.

### CODE REVIEW

**Comment by levithomason** [comment]
Oh boy, thank you for the fix!  I'll add some tests for this.

**Comment by levithomason** [comment]
I'll release this as soon as CI passes and I merge the tests for this util.  Don't want this happening again!

**Comment by levithomason** [comment]
Alright, you can give `semantic-ui-react@0.60.2` a shot now.  It also includes a fix for a `null` document/window.

**Comment by dcurletti** [comment]
@levithomason works great.  Wahoo.  Thanks!

**Comment by levithomason** [comment]
Awesome, glad we got it solved.  Thanks for your help!

**Pull request merged**
