### PR TITLE
docs(DropdownExamplePointing): Fix nested Dropdown

### PR DESCRIPTION
**Pull request by Jimeno0**
Fix nested dropdown little bug just by adding <Dropdown> inside the <Dropdown.Item> submenu
Hope it helps! 
🍺

### CODE REVIEW

**Review by layershifter — CHANGES_REQUESTED** [review]
@Jimeno0 Thanks for PR, can you please fix a lint issue with `Icon`?

**Comment by Jimeno0** [comment]
I think that the linting error (unused Icon import ) its now fixed

**Comment by levithomason** [comment]
This looks great, we should update all the nested Dropdown examples in this PR.

**Comment by levithomason** [comment]
This would also allow us to remove the warning message above many of the examples.

**Comment by mwakerman** [comment]
How come this hasn't been merged? Are you waiting for the banners to also be removed?

**Comment by levithomason** [comment]
This PR updates one of several examples.  Also, some banners could be removed after the updates. 
 However, some progress is better than none.  Will release this soon.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.77.0`

**Pull request merged**
