### PR TITLE
feat(TextArea): add `autoHeight` prop

### LINKED ISSUE #982: Textarea does not auto height
The content of textarea may be very long. The height of textare should flow the content. Please update. This libray made my day. Thank you. Awesome!!!!

### PR DESCRIPTION
**Pull request by luski**
Fixes #982

Tested on Chrome and Firefox. I'll provide test cases in further commit in the nearest future

### CODE REVIEW

**Comment by luski** [comment]
I have no idea how to write tests checking if height of the textarea element changed. Any clues?

**Comment by levithomason** [comment]
Thanks for getting this going.  I've refactored it a bit, adding docs and tests.  LMK if anything looks out of place.  I'll get a final review on this and merge once tests pass and you sign off on my updates.

**Comment by levithomason** [comment]
Also, can you please update the PR description so it closes the issue when merged?  Docs [here](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by luski** [comment]
Looks great, thanks.
resolves #982 - is it enough to close the issue when merged?

**Comment by levithomason** [comment]
Cool, thanks.  There seems to be a 1px rendering difference on CI than locally.  I'll try to fix this.

The comment will need to be in the main description of the PR to close the issue 👍

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.63.2`.

**Pull request merged**
