### PR TITLE
 test(mixed): add test for `content` prop, remove useless tests

### PR DESCRIPTION
**Pull request by layershifter**
Required by #1879.
Requires #2145.
Requires #2152.

### What?

In #1364 we decided that each component that has `children` should also have `content` prop. 

This PR:
- removes all non-common tests for `content` (fewer changes in #1879)
- adds common tests `content` prop (same as for `children`)
- adds `content` prop to all components that missing it

### CODE REVIEW

**Review by layershifter — COMMENTED** [review]
It's ready, requires cleanup and rebase after #2145 and #2152 will be merged.

**Comment by levithomason** [comment]
Unblocked, needs conflicts resolved.

**Review by layershifter — COMMENTED** [review]
@levithomason I solved merge conflicts, ready for review :+1:

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.75.0`

**Pull request merged**
