### PR TITLE
fix(Dropdown): search does not preserve value

### LINKED ISSUE #3552: Dropdown: Search does not preserve value
## Bug Report

When searching for values with the dropdown, the searched value is not preserved in the next consecutive search.

### Steps
A clear and concise description of steps to reproduce the problem.

Consider "Search Dropdown" from the documentation page.

Normal Behavior:

1. Open Dropdown values
2. Click on any value
3. Click inside the dropdown again
4. Value is preserver

Error Behaviour

1. Open Dropdown values
2. Search for any value
4. Click on this value
3. Click inside the dropdown again
4. Value is LOST ;(

ReactBug

### Expected Result

Selected value will be preserved

### Actual Result

Value is lost

### Version

Latest

### Testcase

You can just use your documentation page
ReactBug

### PR DESCRIPTION
**Pull request by mihai-dinculescu**
Fixes #3552.

### CODE REVIEW

**Comment by aschumahua** [comment]
Hi @mihai-dinculescu ! How soon can we get this change?

**Comment by maxnathaniel** [comment]
Does this fix work? If so, can we merge this ASAP? Thank you.

**Review by layershifter — APPROVED** [review]
Will add UTs and will merge 👍

**Comment by maxnathaniel** [comment]
Thanks for the fix and merge! Wondering if there is a tentive date for v0.88.0 release?

**Comment by layershifter** [comment]
I am planing to make it during next week, there will be no breaking changes so it should be `0.87.2`.

**Comment by maxnathaniel** [comment]
Great, looking forward! Thank you

**Comment by RRSR** [comment]
Hi team, I have updated my `semantic-ui-react` version to 0.87.2 from 0.84.0. But I am facing an issue related to dropdown, where after typing a search text if I select an option from the filtered out list that element get selected **but the element at the same index get highlighted too**. I am unable to reproduce the same in [codesandbox](https://codesandbox.io/s/semantic-ui-react-mkkjq).

Any help is appreciated.
Thanks.

**Pull request merged**
