### PR TITLE
chore(package): add types property

### LINKED ISSUE #2856: Unexpected type errors using future versions of typescript
## Bug Report

Whilst testing out future typescript releases I ran into some type errors that weren't popping up before.

### Steps
Transpile a project using `typescript` and `semantic-ui-react`.

### Expected Result
Should transpile without problems.

### Actual Result
Receive type errors like the following:

```
ERROR in /Users/User/project/src/Component.tsx(2,10):
TS2305: Module '"/Users/User/project/node_modules/semantic-ui-react/dist/commonjs/index"' has no exported member 'Input'.
```

### Version
* `typescript@insiders` & `typescript@next`
* `semantic-ui-react@0.80.2`

### Testcase
I can't share the code but the issue is basically that typescript isn't finding the type definitions. This can be solved by adding `"types": "index.d.ts"` to the `package.json`.

### PR DESCRIPTION
**Pull request by traverse**
Fixes #2856

### CODE REVIEW

**Review by layershifter — APPROVED** [review]
Tested this change recently 👍

**Comment by gyandeeps** [comment]
This is breaking builds on typescript 2.9. Any ETA on release?

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.81.0`.

**Comment by levithomason** [comment]
ETA 0s

**Pull request merged**
