### PR TITLE
feat(Dimmer): add transition

### PR DESCRIPTION
**Pull request by layershifter**
# WIP

### CODE REVIEW

**Comment by levithomason** [comment]
Very cool, can't wait to get Transitions in the entire framework :)  This is largely what is stopping a v1 release.  The other blocking work is minor in comparison.

**Comment by tim-soft** [comment]
I have been scratching my head over the dimmer transitions used in the docs site, can't wait for this!

**Comment by levithomason** [comment]
It would be great if we tackled #837 and made `transition` a prop on every component possible.  We'd just need a HOC that did something like (warning, untested!):

```jsx
import React from 'react'
import Transition from './modules/Transition/Transition'

const withTransition = Component => {
  const WithTransition = props => {
    const { transition } = props

    const element = <Component {...props} />

    if (!transition) return element

    return Transition.create(transition, {
      defaultProps: { 
        ...props,
        children: element,
      },
    })
  }

  return WithTransition
}
```

This requires adding a shorthand factory to the `Transition`.

Then, in our component files:
```jsx
// Button.js
export default withTransition(Button)
```

Now, we can do this:

```jsx
<Button transition='fade' />
<Button transition={{ animation: 'fade', duration: 100 }} />
```

I actually did this for `popup` and I cannot find the branch 😭 The only issue I had was getting the docs to understand extended propTypes.  Example, the Button above would need to spread the `withTransition` propTypes.  I guess we could just hard code them, but it would be nice to be able to inherit.  Especially as we'll have propTypes from `withPopup` and any other HOCs we add.

**Comment by layershifter** [comment]
In fact, the key problem that I see there is with `page` `Dimmer`. Instead of regular in renders inside `Portal` which unmounts its content when it closes. I'm still have no idea how to resolve this without tons of callbacks.

**Comment by layershifter** [comment]
Needs #2155.

**Comment by levithomason** [comment]
TransitionablePortal has been merged, unblocking this.

**Comment by padrefuture** [comment]
New to this site, and Im hoping this is the right place to post this. Im looking for a a menu with an animated (transition?) dropdown, that has a delay on mouseout. ANy ideas where i can find or is this too much to ask in the SemanticUI/React world?

**Comment by levithomason** [comment]
@padrefuture animations are a work in progress here in the React port of Semantic UI.  That feature is not yet available.  We do have a [Transition component](https://react.semantic-ui.com/modules/transition).  That component needs to be integrated into our components so we have the transitions you are looking for.  PRs welcome!

**Comment by ghost** [comment]
Am I wrong or is just a linting problem the latest ci/circleci problem?

Can we force this and then fix the lint problems?

I'm newbie, sorry for maybe wrong questions.

**Comment by levithomason** [comment]
I've merged master and fixed the lint issues.  This PR still appears to be in progress, as the description states.

We'll need the feature completed, some tests, and some docs.

**Comment by jermsam** [comment]
Hey guys. Any success with @levithomason 's sugestion? I don't see myself moving away from semantic ui react just because of a simple animation. This css framework is awesome for react. someone do something please

**Comment by brianespinosa** [comment]
Good morning @jermsam 

This is an open source project and anyone is welcome to contribute. If there is an area of the framework where you have a need for something specific to your project, pull requests are always welcome.

**Comment by ghost** [comment]
@stale, please, shut up.

**Pull request closed without merging**
