### PR TITLE
fix(Popup|Portal): do not close when mouse click was occurred inside

### PR DESCRIPTION
**Pull request by mihai-dinculescu**
This PR is my proposed fix for #3554.

Afaik the `onClick` event provides no information whatsoever about the position where the mouse button was pressed down. For this reason I've added a listener for `mouseDown` and I'm storing the latest occurence of this event in the component.

~~I would like to also write a unit test but I'm not really sure how to go about mocking a click that originates in one place and ends in another.~~

### CODE REVIEW

**Comment by mihai-dinculescu** [comment]
~~I've updated `domEvent.click` to also fire `mousedown` and `mouseup` so that it mimicks reality.~~

**Comment by layershifter** [comment]
@joergbaier @mihai-dinculescu Thank you for addressing this 👍 

We have a similar stuff in `Dropdown` with `isMouseDown` and I prefer to keep existing listeners with `click` instead of `mouseup`. So I am wondered, do we really need to use `document.mouseup` instead of `document.click`?

**Comment by mihai-dinculescu** [comment]
I don't see any way around using `mousedown`. `click` provides no information whatsoever about it.

However, I do see why we need to be more thoughtful before merging this. Touch gestures do not provide `mousedown` and `mouseup` events.

After further consideration, I now think that we should use `mousedown` in tandem with `click`, instead of `mousedown` and `mouseup`.

I should have a rework of this branch ready soon.

**Comment by mihai-dinculescu** [comment]
Ok @layershifter, it should look much better now!

**Pull request merged**
