### PR TITLE
feat(config): possibility to modify default link element

### PR DESCRIPTION
**Pull request by tomitrescak**
As per discussion in #378

### CODE REVIEW

**Comment by levithomason** [comment]
Couple lint errors:

```
/home/ubuntu/stardust/src/lib/config.js
  3:19  error  Missing trailing comma                         comma-dangle
  4:2   error  Newline required at end of file but not found  eol-last
```

Did you plan on wiring this in anywhere, or just adding the config for now?  Thanks much!

**Comment by levithomason** [comment]
@tomitrescak it looks like this PR includes typings also now.  We'll to merge only the config for this PR.  I suggest creating a branch off of your master that only has the config work on it so only that work will be merged.  Alternatively, you could keep this PR open and just temporarily remove the typings so only the config is being proposed.

**Comment by tomitrescak** [comment]
I have removed typings from this PR and will create new one

**Comment by jeffcarbs** [comment]
In it's current state, I'm not sure this is something we should add. For the use-case referenced in #378 (usage with `react-router`) this won't actually have any effect. The `Link` doesn't actually do anything unless there's a `to` prop (see: https://github.com/ReactTraining/react-router/blob/master/modules/Link.js#L116).

My issues:
- This is very a specific use (only elements where an `href` prop is passed) and it already doesn't work with one of the main React-based routing libraries. This is probably the biggest red flag.
- Wherever this would be working, you're already going to be passing a path as a prop (whether via `href` or `to` or whatever your library calls for). I don't think adding `as={Link}` adds much more complexity so I don't think this really saves a lot of work.

@levithomason - would love your thoughts here as well.

**Comment by levithomason** [comment]
Although the original intent of the config was for an i18n function and I think we should allow that, I agree that users should use `as={Link}` instead of allowing an `anchorElement` config option.

Thanks @jcarbo for the clarification.  Apologies @tomitrescak as I had not fully realized the goal here.  If you'd like to use an element as a `Link`, you should do so like this:

``` jsx
<Menu>
  <Menu.Item as={Link} to='/home'>
    Home
  </Menu.Item>
</Menu>
```

See: http://react.semantic-ui.com/introduction#augmentation

**Pull request closed without merging**
