### PR TITLE
docs(Portal): fix controlled Portal usage

### LINKED ISSUE #3408: Portal: controlled portal is not closed on button click
### Steps
https://react.semantic-ui.com/addons/portal/#types-controlled

1.  Click "Open portal"
2. Click  "Close portal"

### Expected Result
Portal closed

### Actual Result
Portal is not closed

### Version
0.84.0

### Testcase
Docs: https://react.semantic-ui.com/addons/portal/#types-controlled

### PR DESCRIPTION
**Pull request by Fabianopb**
As discussed in #3408 the usage of `Portal` as a controlled component was wrong in the docs creating a false positive bug. The proper way puts the control inside the `Portal`'s `trigger`:

image

(Closes #3408)

### CODE REVIEW

**Comment by layershifter** [comment]
Actually, the issue comes from EventStack that incorrectly works with browser frames (click on `button` should not be fired actually).

There is an experiment with new approach: https://codesandbox.io/s/9yw3vq6774 I need to spend more time on it to test other scenarios and perform cleanup.

I will update the example later today.

**Comment by Fabianopb** [comment]
So would that mean that the fix should be done in EventStack in the end?

**Comment by layershifter** [comment]
> So would that mean that the fix should be done in EventStack in the end?

@Fabianopb Actually, yes. But, I'm not ready to ship a _correct_ fix for right now. I need to resolve the issue correctly and forever 👍

**Review by layershifter — APPROVED** [review]

**Comment by layershifter** [comment]
@Fabianopb I've updated an example, now it works more correctly. Please let me know if it is fine 🚶

**Comment by Fabianopb** [comment]
Now the external button is solely used to open the `Portal`, which can be closed via the internal button or by clicking outside. Sounds fair too!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.86.0`.

**Pull request merged**
