### PR TITLE
Fix(Portal) check for rootNode rendering to prevent race condition 

### PR DESCRIPTION
**Pull request by Brantron**
We rely heavily on Semantic-UI-React and have had our monitoring reporting the following issue
```
TypeError: Cannot read property 'firstElementChild' of null
```

We've investigated it a few times but recently stumbled upon this issue https://github.com/Semantic-Org/Semantic-UI-React/issues/2401

This commit has been able to successfully prevent this issue without introducing any new issues.

### CODE REVIEW

**Comment by levithomason** [comment]
Let's add a failing test that validates the fix.  The fix location is also suspect. If `this.rootNode` were `null` or `undefined` at line 364, where the check is currently, then [line 354](https://github.com/Brantron/Semantic-UI-React/blob/5077c28ed04c8306773a48350b301b4561cb6b83/src/addons/Portal/Portal.js#L354) would throw a TypeError before ever reaching that point:
```jsx
    this.rootNode.className = className || ''
```

**Comment by Brantron** [comment]
@levithomason, excellent point. I dug a little further and came across https://github.com/facebook/react/issues/9808 which highlights

> The problem is `unstable_renderSubtreeIntoContainer` is async and can be called after `componentDidUpdate`. When refs are used in `componentDidUpdate`, they can be undefined due to async nature of `unstable_renderSubtreeIntoContainer`.

Thanks for the guidance. I've refactored a bit and added a test.

**Comment by Brantron** [comment]
@levithomason ping

**Comment by levithomason** [comment]
Ah, nice find!  I've done some manual testing and this all looks great.  Thanks for the detective work.

**Comment by aloey** [comment]
Thank you so much for resolving this issue!
Any chance you will be updating the npm package soon?

**Comment by levithomason** [comment]
Released in `semantic-ui-react@v0.78.0`.

**Comment by levithomason** [comment]
@aloey I shoot for a release every weekend.  Sometimes life prevents it.

**Comment by JsGvDev** [comment]
Thanks folks to fix this error. I've spent a few hours to find out about this bug, because I only  could get this error from Portal but into 'node_modules/react/cjs/react.development.js', until I can isolate that error. Nothing into the app is broken, everything was working fine, but I got that error #2401 from console. I was using semantic-ui-react@v0.76.0, after updating semantic-ui-react@v0.78.0 that error is gone.

**Pull request merged**
