### PR TITLE
fix(Dropdown): update text when item selected with keyboard

### LINKED ISSUE #2161: Dropdown: Does not display value on enter when using search selection
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - http://stackoverflow.com/search?q=semantic-ui-react

✔ BUGS → This form is required:

### Steps
```
<Form.Dropdown
      label={label}
      search
      selection
      selectOnBlur={false}
      selectOnNavigation={false}
      options={options}
      value={input.value}
      onChange={(param,data) => input.onChange(data.value)}
    />
```

Search a couple of letters in dropdown search selection
Arrow down to selection
Hit enter

### Expected Result
Call onChange and displays new value in input box

### Actual Result
Calls onChange but displays the searched letters instead of new value
OnBlur sets display of input box to value

### Version
0.74.2

### Testcase
[Fork, update, and replace this pen to show the bug]:
http://codepen.io/levithomason/pen/ZpBaJX

### PR DESCRIPTION
**Pull request by ayastreb**
Fixes #2161 
the text on dropdown wasn't updated when item is selected with keyboard after search because `searchQuery` wasn't cleared if there are multiple search results (it is cleared if there's only one search result). And if `searchQuery` is not cleared, we do not update text in [renderText](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L1136)

### CODE REVIEW

**Comment by layershifter** [comment]
@ayastreb Thanks for the PR, this needs more investigation as it's opposite change to #2112

**Comment by layershifter** [comment]
Our behaviour should match to SUI:
- https://semantic-ui.com/modules/dropdown.html#search-selection
- https://semantic-ui.com/modules/dropdown.html#multiple-search-selection

**Comment by layershifter** [comment]
In fact, problem comes from condition with `optionSize`, which was added in #1956. As I think, we should clear `searchQuery` **always**, all other cases can be manually handled by user with [`searchQuery` prop](https://react.semantic-ui.com/modules/dropdown#dropdown-example-search-query).

As I see the following change will not break any test:
```diff
-if (isAdditionItem || optionSize === 1) this.clearSearchQuery()
+this.clearSearchQuery()
```

@levithomason can you clarify?

**Comment by levithomason** [comment]
Always clearing seems like the correct solution to me.  @ayastreb are there any issues with this feature if we always clear the search query?

**Comment by ayastreb** [comment]
@levithomason seems to be no issues, all tests are green and it works as expected.

**Comment by levithomason** [comment]
Thanks guys!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.75.0`

**Comment by scottrblock** [comment]
Hi @ayastreb and @levithomason, I'm curious as to why this is only the expected behavior if the item is selected with a keyboard. It currently seems that if there are multiple options and one is clicked with the mouse, the searchQuery is not cleared.

This can be handled by locally managing the `searchQuery` state and clearing it `onClose`, but I would expect the same default behavior for selecting an item from the keyboard or mouse.

**Comment by levithomason** [comment]
Agreed.  It should be consistent.  This was an oversight.  A new issue and PR would be much appreciated.

**Pull request merged**
