### PR TITLE
breaking(Popup): rename `positioning` to `position`

### PR DESCRIPTION
**Pull request by kamdz**
as requested in #1259

### CODE REVIEW

**Comment by levithomason** [comment]
Great, thanks!  I'm going to try and ship this with the other breaking change coming up, #1038.

**Comment by levithomason** [comment]
@kamdz is there anyway you could move this PR to a branch in your fork so I can make updates as well?  I'd like to merge this one, but it has some updates that are needed now.

**Comment by kamdz** [comment]
@levithomason you mean I need to update my branch to latest master and resolve conflicts?

**Comment by kamdz** [comment]
I created new pr

**Pull request closed without merging**
