### PR TITLE
Modal, Portal and Popup

### PR DESCRIPTION
**Pull request by iamdanthedev**
1) This addresses the problem of portal stealing the focus
https://github.com/Semantic-Org/Semantic-UI-React/issues/1324
**Popup**: added prop focusOnRender (bool)
**Portal**: added prop focusOnRender (bool, default true)

2) This addresses the issue, which allows user to close modal (by clicking outside or hitting esc) and we should be able to check if closing the modal is possible (for example changes inside the modal haven't been saved)
**Modal**: onClose callback allows to cancel closing modal if false is returned

3) This solves the problem of opening a modal with a scroller inside a modal with a scroller. When the upper modal is closed it reverts the original modal's scroller function back (otherwise lower modal loses a scrollbar)
**Modal**: mountNode original classnames are saved in modal state and reverted when modal is unmounted

Please let me know if this goes inline with the concept of SUI-React, than I could polish this changes or something..

Thanks, with respect, Dan

### CODE REVIEW

**Comment by levithomason** [comment]
For now, we only want to revert the focus on open behavior.  If users need to focus a portal component, they will implement their own focus mechanisms.

Would you like to make a PR doing only this and we can address these other items separately?

**Comment by iamdanthedev** [comment]
Ok I will try to make a proper PR on the first issue, going through all portal-based components.
Regarding others it will probably take some time to dig through all components
Ping soon, thanks

**Comment by levithomason** [comment]
Heads up, I needed the original focus fix so I fixed that and shipped it a couple hours ago.

**Comment by iamdanthedev** [comment]
Oh, I got it and that's great. Anyway will try to contribute soon. The lib is really helpfull

**Comment by layershifter** [comment]
@levithomason Seems, we can close this for housekeeping.

**Comment by levithomason** [comment]
Agreed, looks like most, if not all, of these fixes are released.

**Pull request closed without merging**
