### PR TITLE
fix(Dropdown): display icon in selected text

### PR DESCRIPTION
**Pull request by rbideau**
First attempt at fixing #1147

### CODE REVIEW

**Comment by levithomason** [comment]
@rbideau what is the status on this one?

**Comment by rbideau** [comment]
I didn't spent any time on it lately, but I'm still stuck at the same point as I said in #1147.

It's in [line 990 of src/modules/Dropdown/Dropdown.js](https://github.com/Semantic-Org/Semantic-UI-React/pull/1172/files#diff-609214949026e594dbfd98481664c928R990) of this PR.

**Comment by levithomason** [comment]
The DropdownItem's create method does not set children:

https://github.com/Semantic-Org/Semantic-UI-React/pull/1172/files#diff-39c9e693d6f8be797267ef676395ef14R171

```diff
-DropdownItem.create = createShorthandFactory(DropdownItem, value => value)
+DropdownItem.create = createShorthandFactory(DropdownItem, children => ({ children }))
```

The callback above is invoked when the shorthand value is a string, number, or an array.  This change will map those values to the children of the DropdownItem so that:

```jsx
DropdownItem.create('item 1')
// => <DropdownItem>item 1</DropdownItem>
```

**Comment by rbideau** [comment]
This doesn't work because when there is an icon, `rest` is an object and then [mapValueToProps is not called in factories/createShorthand](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/factories.js#L37-L39)

**Comment by levithomason** [comment]
This PR has gotten stale and seems abandoned.  Closing for housekeeping.  Still happy to merge an updated and complete community PR.

**Pull request closed without merging**
