### PR TITLE
feat(Visibility): add component

### PR DESCRIPTION
**Pull request by mariolamacchia**
Related to #1173.

## Todo

- [x] standard events
- [x] grouped events
- [x] reverse events
- [x] settings

### CODE REVIEW

**Comment by levithomason** [comment]
@mariolamacchia any update here?

**Comment by mariolamacchia** [comment]
@levithomason I've been quite busy, I'll try to work on this during the week

**Comment by mariolamacchia** [comment]
@levithomason I think this should be enough for a first PR. I implemented all the callbacks and the main settings. Let me know what you think about it.

**Comment by levithomason** [comment]
Apologies for the delay!  This is looking great.  A couple requests:

1. Can we get the visibility info to be sticky in the docs?
1. Let's go with `behaviors` spelling.

**Comment by mariolamacchia** [comment]
> Can we get the visibility info to be sticky in the docs?

What's the status on #198? If it's not ready I can implement a custom sticky component for the demo.

> Let's go with behaviors spelling.

Right

**Comment by levithomason** [comment]
The sticky component seems to be stalled.  There is no active development.

>If it's not ready I can implement a custom sticky component for the demo.

This would be fantastic!  It would seem to me that the Visibility component would power the Sticky component very nicely.

If you're up for doing this, we can just add/fix tests and merge this one now and then make another PR right away that implements Sticky.  This way, we don't end up with too much bloat here.

**Comment by da-moon** [comment]
@mariolamacchia Any updates?

**Comment by mariolamacchia** [comment]
Sorry, it slipped my mind 😓 , it should be ok now.

I'll start with the sticky as soon as this is merged to master.

**Comment by levithomason** [comment]
We can merge this as soon as the conflict in `test/specs/commonTests.js` is resolved.

**Review by layershifter — APPROVED** [review]
I've solved a conflict, however I wan't push some style updates there and create typings.

**Comment by mariolamacchia** [comment]
@layershifter Thanks, let me know if I can help

**Review by layershifter — APPROVED** [review]
I've pushed all changes that I wanted to make.

@levithomason We're ready for review there.

**Comment by kevinluvian** [comment]
any updates on this?

**Comment by levithomason** [comment]
🎉

**Comment by da-moon** [comment]
@mariolamacchia Hey man , thank you so much for working on this component. Any chance that you will be able to write some examples on how to use it?

**Comment by mariolamacchia** [comment]
@damoonazarpazhooh there are some [example in the docs](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/docs/app/Examples/behaviors/Visibility), it should be pretty straightforward :)

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.4`.

**Pull request merged**
