### PR TITLE
fix(eventPool): check existance of handler in EventTarget._unlisten

### PR DESCRIPTION
**Pull request by mhagmajer**
Fixes https://github.com/Semantic-Org/Semantic-UI-React/issues/2120

### CODE REVIEW

**Comment by mhagmajer** [comment]
Failing check seems like false negative

**Comment by layershifter** [comment]
@levithomason I've marked this as ready for review, however I'm not sure that this is fixes something. We don't have reproduction and I don't see how this can be covered by unit tests.

**Comment by levithomason** [comment]
As I've shown here https://github.com/Semantic-Org/Semantic-UI-React/issues/2120#issuecomment-340239605, both our code and the browser's native code already gracefully handle removing `undefined` handlers.  I want to get a broken test case that this fixes before merging.

**Comment by levithomason** [comment]
I should note, I spent 20-30 minutes researching and also trying to reproduce this.  I could not do so in Chrome nor PhantomJS no matter what abuse I threw at our EventTarget and eventStack. I was also unabled to reproduce this in Chrome with `removeEventListener`.

The closest I could find was this https://github.com/angular/zone.js/issues/21 issue.  They had this error, but they also seemed unable to reproduce it.  It seemed to resolve itself, unfortunately.

Lastly, neither `_bound` nor `bound` are properties that occur in our codebase.  This leads me to believe the error is something native to the browser, or some other conflicting lib.

**Comment by levithomason** [comment]
Any more progress on this one?

**Comment by mhagmajer** [comment]
Not yet, I'll get back to you when I have something

**Comment by layershifter** [comment]
Closing for housekeeping. Will be reopened if we will have a repro case.

**Pull request closed without merging**
