### PR TITLE
refactor(project): stardust => semantic-ui-react

### PR DESCRIPTION
**Pull request by levithomason**
This PR renames stardust references to semantic-ui-react in preparation for migration:

```
Stardust                            =>      Semantic-UI-React
stardust                            =>      semantic-ui-react
```

``` js
import { Button } from 'stardust'   =>      import { Button } from 'semantic-ui-react'
import * as stardust from 'src'     =>      import * as semanticUIReact from 'src'
```

```
window.stardust                     =>      window.semanticUIReact
localStorage.stardust               =>      localStorage.semanticUIReact
```

### CODE REVIEW

**Comment by jeffcarbs** [comment]
Pulled this down locally and `stardustCompleter` was the only reference I saw that still needs to be changed.

**Comment by levithomason** [comment]
Thanks, working on the doc site editor import rewrite magic/hack ATM.  Once I get that done, I'll manually test the doc site and browser build.  If all that checks out, then we're good publish under the new module name for the first time!

**Comment by levithomason** [comment]
Oh boy, a little nervous to push this button :S Here goes!

**Comment by levithomason** [comment]
OK, released as `semantic-ui-react@0.53.0` 🎉 

I expect some triage to follow...

**Pull request merged**
