### PR TITLE
docs(build): use react-static for prerender

### LINKED ISSUE #2826: Prerender docs on the server side
## Feature Request

Improve the SEO for Google etc. by adding a sitemap and a robots.txt

### Problem description

When we search e.g. for "semantic ui react label", no result for the react label will appear:

image

### Proposed solution

- add a sitemap.xml
- add a robots.txt which refer to the sitemap

### MVP

Best way would be to not hard code the sitemap. So maybe we could generate the links?

I'm also not sure, if this repo is the correct place for such an issue. I haven't found the repository for the semantic ui react documentation page yet.

## Edit:

 I tried to find the URLs in Google by searching for `site:https://react.semantic-ui.com/elements/label`.
=> Google has indexed the result, so maybe just the SEO is very bad on these pages? idk

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2826.

### CODE REVIEW

**Comment by layershifter** [comment]
It's finally ready! ✌️ 

### Testing

##### Develop build
`yarn start`

##### Staging build

1. Update [`docs.js`](https://github.com/Semantic-Org/Semantic-UI-React/blob/5ac819243abb51492d091d5ebfdfce6fe0f01e34/gulp/tasks/docs.js#L60)

```diff
-build().then(cb)
+build({ staging: true }).then(cb)
```
2. `yarn build`
3. `yarn serve docs/dist`

**Comment by levithomason** [comment]
👍 pushed a fix to `.gitignore` for the `/tmp` directory
👍 The development workflow with `yarn start` works OK

⛔️ Changing `docs.js` to `build({ staging: true })` and running `yarn build` produces this error:

```
[12:43:17] Starting 'build:docs:static:build'...

ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (static.routes.js:28:1)
    at Module._compile (module.js:652:30)
    at Module._compile (node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

(node:31600) UnhandledPromiseRejectionWarning:
    TypeError: Cannot read property 'DIST' of undefined
    at _callee$ (node_modules/react-static/lib/commands/build.js:73:58)
    at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next]
        (node_modules/regenerator-runtime/runtime.js:117:21)
    at step (node_modules/react-static/lib/commands/build.js:31:191)
    at node_modules/react-static/lib/commands/build.js:31:437
    at new Promise (<anonymous>)
    at node_modules/react-static/lib/commands/build.js:31:99
    at build (node_modules/react-static/lib/commands/build.js:165:17)
    at gulp/tasks/docs.js:60:3

(node:31600) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
             This error originated either by throwing inside of an async function
             without a catch block, or by rejecting a promise which was not handled
             with .catch(). (rejection id: 2)

(node:31600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
             In the future, promise rejections that are not handled will terminate the
             Node.js process with a non-zero exit code.

[12:43:17] The following tasks did not complete:
           build, <parallel>, build:docs, build:docs:static:build

[12:43:17] Did you forget to signal async completion?
```

I debugged this for a bit but could not get anywhere.

**Comment by layershifter** [comment]
@levithomason React-Static forces the usage `regeneratorRuntime`. However, I think we don't need it for our builds. So this configured with `NODE_ENV`, [ref](https://github.com/Semantic-Org/Semantic-UI-React/pull/2925/commits/42fa631063110454113e46b73988c8e2bcfa0eb6#diff-dae29ed0ddce4ecdabc211bf04cced30R26).

It seems that I've forgotten to update `package.json`, because I've tested with `yarn prerelease`.
Pushed a small commit with an update, my fault 😼

**Comment by layershifter** [comment]
@levithomason resolved merge conflicts 👍

**Pull request merged**
