### PR TITLE
docs(layouts): make HomepageLayout responsive

### PR DESCRIPTION
**Pull request by layershifter**
Fixes: #2386

### CODE REVIEW

**Comment by layershifter** [comment]
@brianespinosa Your feedback is much needed there

**Comment by brianespinosa** [comment]
@layershifter just getting back from the holidays. I just assigned this to myself and will take a deeper look later this afternoon. 👍

**Comment by dongcai** [comment]
@layershifter & @brianespinosa I think this solution breaks the Server Side Rendering. I actually tried to do the similar thing at: https://github.com/dongcai/react-redux-semantic-ui/blob/master/src/components/Navigation/Navigation.js
And found that the code like `<responsive>{children}</responsive>` will break the SSR, which I would like `{chidren}` to be rendered by.  Any ideas?

**Comment by layershifter** [comment]
@dongcai please make a minimal repro repo and open new issue.

**Comment by brianespinosa** [comment]
@layershifter Sorry... my workload exploded this month. I haven't even been on github in two weeks. I will try to get some eyes on this by Monday. Apologies for the delay.

**Comment by brianespinosa** [comment]
Thanks @layershifter 

Additionally... I meant to bring this up here and with @levithomason , it might be good to update the layout of the docs in general to make the side menu available to toggle on/off. Maybe just update the style of the docs in general in preparation for 1.0.

But I think this looks good for now. 👍

**Comment by levithomason** [comment]
Definitely agree.  We should use the actual Sidebar component.  I think it needs #1408 before that can be done properly.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@v0.78.0`.

**Pull request merged**
