### PR TITLE
add meteor url for usage

### PR DESCRIPTION
**Pull request by Maxhodges**
merge this 877 before https://github.com/Semantic-Org/Semantic-UI-React/pull/878

### CODE REVIEW

**Comment by levithomason** [comment]
Would you mind adding this one liner to the other PR?

**Comment by Maxhodges** [comment]
can I still edit it once I submit? I'm not really a pro with merging pull
requests

_Max Hodges_ | Partner at White Rabbit Japan http://whiterabbitjapan.com |
t 03.6450.7109 | m 090.1795.4446

**Comment by levithomason** [comment]
I would just close this one, and add the one line change to the other PR 👍

**Comment by levithomason** [comment]
Closing in favor of the other PR.

**Pull request closed without merging**
