### PR TITLE
docs(Portal): add Example under Addons Section of Docs

### PR DESCRIPTION
**Pull request by alexUXUI**
Documentation Update
Adds Portal Example

Hello, I have added a simple yet functional example of the SUI Portal component. It mainly demonstrates the callback functions that are available through the Portal component API. It is not exhaustive but would provide a good starting point for future iterations. 

There is only one problem with the way that this example fits (or does not) fit into the documentation website. Because of the positioning that is baked into of the Portal component, it is rendering underneath the left navigation of the website. I am unsure the best way to resolve as I do not want to add css. 

Many thanks to the maintainers and authors of this library. it is a true gem and I would love to be a part of the awesome community around it.

### CODE REVIEW

**Comment by alexUXUI** [comment]
Hmm, I do not see a place to add test coverage to the example I have provided in docs/app/examples. I do see an example test in test/specs/docs/examples-test. I am not sure what I am missing in terms of testing but would like to provide - just need a little guidance.

**Review by layershifter — CHANGES_REQUESTED** [review]
@alexUXUI Please restore files' permissions.

**Comment by alexUXUI** [comment]
@layershifter oh, silly me! Will do now.

**Review by layershifter — APPROVED** [review]
@alexUXUI Thanks for PR. I've restored permissions and pushed some style changes @levithomason we're ready for review there

**Comment by levithomason** [comment]
Great, thanks!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.4`

**Pull request merged**
