### PR TITLE
fix(Portal): make compatible with React Fiber

### PR DESCRIPTION
**Pull request by cpunion**
Tested with react@15.4.2 and react@16.0.0-alpha4

Fix https://github.com/Semantic-Org/Semantic-UI-React/issues/1458

### CODE REVIEW

**Comment by levithomason** [comment]
Excellent work!  I've checked the source and it appears the callback is indeed called on completion.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.2`.

**Comment by cpunion** [comment]
Thanks!

**Comment by jpollard-cs** [comment]
you could have used v16's [unstable_createPortal](https://github.com/facebook/react/blob/7d2be2c9a7b4a976e20d2d7c312b43b1bee01a07/src/renderers/dom/fiber/ReactDOMFiber.js#L212) 😄

**Comment by levithomason** [comment]
Guessing this would abandon React v15 users?

**Comment by jpollard-cs** [comment]
move fast and break things! 

wasn't entirely a serious comment

**Pull request merged**
