### PR TITLE
fix(Dropdown): sets focus to the search input after selection

### LINKED ISSUE #3349: Dropdown: focus is lost after selection
Drop-down looses focus when I select an item, can anyone please tell me how should I maintain focus.

### PR DESCRIPTION
**Pull request by jongsue**
Addresses #3349.

focus-after-selection

### CODE REVIEW

**Comment by Fabianopb** [comment]
Next time just take a look if someone else has already committed to start working on the issue...

**Comment by layershifter** [comment]
I need to merge #3428 before.
Tried the similar fix today, but there were issues with broken key handlers.

**Comment by layershifter** [comment]
I added some small changes. Actually, this PR don't fix #3349 because the focus will be still lost on usual `<Dropdown selection />`. Going to merge this PR because it fixes the issue for `<Dropdown search selection />`.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.86.0`.

**Pull request merged**
