### PR TITLE
fix(Modal): spread the user's style prop on the Modal

### LINKED ISSUE #1308: Modal window fixed height
Hello

Is there any simple way to open modal at fixed screen height (minus margins) ?
By default a modal window tries to center itself vertically which causes problematic UX when modal content changes

### PR DESCRIPTION
**Pull request by rajchourasia**
Fixes #1308

### CODE REVIEW

**Comment by layershifter** [comment]
@rajchourasia It will be awesome if we add test there. And we also need to add prop to typings.

**Review by layershifter — APPROVED** [review]
@rajchourasia Thanks for PR!

**Comment by levithomason** [comment]
Superb, thanks much!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.2`.

**Pull request merged**
