### PR TITLE
fix(Dropdown): isEqual over shallowEqual for props

### LINKED ISSUE #2243: Dropdown: setState in onChange leads to mismatch of 'active' and 'selected' option
### Steps

I want to setState() by onChange of the Dropdown

### Expected Result

The state should be set and the dropdown should change its value.
The selected option should be active and selected

### Actual Result
The state is set as expected
The selected option is set to active, the previously selected option is kept as selected.
=> **Selected and active do not match the same option anymore**

### Version
0.75.1

### Testcase
https://codesandbox.io/s/lrvqlpy7oz

### PR DESCRIPTION
**Pull request by chrisjbrown**
fixes #2243

Component on `componentWillReceiveProps` will always run `setSelectedIndex` because shallowEqual on two objects internally runs `object.is(a, b)` to compare objects which will always be false because `nextProps.options` and `this.props.options` are not the same object

### CODE REVIEW

**Comment by levithomason** [comment]
Let's get a test here that fails with the workflow reported in the issue.  This way we don't hit the regression again.

`isEqual` was removed as part of the lodash optimizations as it is a very slow and heavy method.  We can use it here if we must, but I'd like to ensure there is a test that catches the failing behavior.

**Comment by chrisjbrown** [comment]
Added UT for when props are updated with options that are the same and when props are updated with new options.

**Comment by levithomason** [comment]
Awesome, thank you very much @chrisjbrown!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.76.0`

**Pull request merged**
