### PR TITLE
Update MenuItem label propType to node

### PR DESCRIPTION
**Pull request by Johnsel**
Hi everyone,

I have made this change to allow the label to be filled with some React component as well, in my case I needed to put in a "FormattedMessage" from the react-intl library to show a potentially translated label.

### CODE REVIEW

**Comment by levithomason** [comment]
Heads up, @awei01 is working on revamping the Menu API entirely (#319) to meet our v1 component API pattern (#269).

We can merge this for now though, but we should probably go ahead and use:

``` jsx
label: PropTypes.node,
```

Which is valid for string, number, React component, or regular DOM node.

**Comment by Johnsel** [comment]
Cool, I did not know that. Will you make the change?

**Comment by levithomason** [comment]
I'll merge it, but I don't have rights to your fork.  Easy win contribution if you like to push the update :)

**Comment by Johnsel** [comment]
Sure, thanks. One minute please...

**Comment by levithomason** [comment]
Thanks much!

**Comment by awei01** [comment]
@levithomason Hi. Sorry, but I won't be able to take on `Menu`. I've been sidetracked onto other projects.

**Comment by levithomason** [comment]
It happens, thanks for the update @awei01.

**Pull request merged**
