### PR TITLE
Add Card component

### PR DESCRIPTION
**Pull request by eanplatter**
# Under Construction

Building the card.

### CODE REVIEW

**Comment by eanplatter** [comment]
Fixes: #186

**Comment by levithomason** [comment]
I've rebased this PR to the latest master for you.  I also added our basic `commonTests`, see [here](https://github.com/TechnologyAdvice/stardust/pull/202/files#diff-843950b62b563fac3014ef7403bcfcfaR8).  I've added the `.only()` call to the `Card-test.js` as well so they are the only the tests that run.

It's been a while since you've hacked on this, so I'd blow away and reinstall node modules.  You should then be able to run `npm run test:watch` and see only the common card tests.  This should get you going as there are many well defined tests to get passing:

image

Cheers!

**Comment by eanplatter** [comment]
:fallen_leaf: sounds good man! Thanks!

**Comment by levithomason** [comment]
Yo @eanplatter, I know you've been busy.  Thanks to @jamiehill and a few others we're getting a lot of momentum.  If we come up on this component, shall we ping you or hop on it?

Let me know what your plans are.  Thanks.

**Comment by levithomason** [comment]
Bump.  Noted the new [CONTRIBUTING.md](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md) docs.  We need to spec out this component's API.

**Comment by eanplatter** [comment]
@levithomason I'd be great to pair on this one of these evenings! I'd like to get a feel for the workflow so I can make contributions whenever I've got time, I've been doing react native lately so my need for stardust hasn't been as present, but as soon as I move back to web stuff I'll be using it.

**Comment by levithomason** [comment]
I'm game for some pairing for sure.  Busy tonight with 3SC, but hit me up on Slack to get a time set.

**Comment by athurman** [comment]
Closing in light of #387

**Pull request closed without merging**
