### PR TITLE
docs(Ads): fix multiple ads

### PR DESCRIPTION
**Pull request by layershifter**
## Issue source

There was a strange tweet about issue with ads, https://twitter.com/ARedHerring_/status/1041044450288590848

I haven't ever seen this, looks really ugly :-1: I tried to find the issue and it seems that it comes from the Carbon's code, it adds multiple adds sometimes.

image

### CODE REVIEW

**Comment by layershifter** [comment]
@levithomason can you please take a look? Possible there is a solution without dirty tricks?

**Comment by levithomason** [comment]
Thanks, this was also reported to me via email.  The refresh method removes the ad then creates a new one.  If there is no ad in the div, it will insert one.  What is happening is that `componentWillUpdate` is called in rapid succession calling refresh multiple times rapidly.  This removes and replaces the ad on the first call, but before it is loaded the second refresh is also called which fetches a second ad.

I will take a look at the changes here and confirm the fix or update it.

**Comment by levithomason** [comment]
- Added check to ensure we don't duplicate fetch ads.
- Made it smaller and better styled, was taking up a lot of real estate.
- Improved sidebar ux and layout to help with real estate.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.83.0`.

**Pull request merged**
