### PR TITLE
fix(Icon): fix typings of Icon.Group

### PR DESCRIPTION
**Pull request by mihai-dinculescu**

### CODE REVIEW

**Review by layershifter — APPROVED** [review]

**Comment by layershifter** [comment]
@mihai-dinculescu Thanks :+1:

**Comment by levithomason** [comment]
@layershifter have a look at your email, you want to take this one? 😉

**Comment by layershifter** [comment]
@levithomason I did :ghost: I will reply you tomorrow :+1:

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.74.0`

**Pull request merged**
