### PR TITLE
[WIP] Animated Accordion API

### PR DESCRIPTION
**Pull request by moaxaca**
Hey guys, 

I've made this in response to issue: https://github.com/Semantic-Org/Semantic-UI-React/issues/2114

Disclaimer: This isn't completed I want to talk to the maintainers on API design. I haven't included test coverage but I will when the API design is solidified.  

I am opening up this PR to promote a conversation on how to expose decorated animated interfaces. I was looking for examples of modules being decorated by Transitions and couldn't find a convention. 

I've included with this PR two ways of accomplishing the behavior one from a new top layer decorator of the Accordion -> AccordionAnimated. Secondly, I've also included a more intrusive example where I define the animation props against the AccordionContent. I don't expose the full transition API in the current implementation and would like to discuss a strategy on doing that gracefully. 

Looking forward to some feedback when you guys get the chance!

Also kudos on the codebase this being my first exposure it was extremely easy to bootstrap and contribute.

### CODE REVIEW

**Comment by brianespinosa** [comment]
Thanks for putting this together @moaxaca. I think we will want some input from @layershifter on this since I believe he had some vision on how we could reduce boilerplate when he created the `Transition` component. Ideally we could have one decorator component that could be reused on other components that is not specific to `Accordion`. So the `AccordionAnimated` component would be something more generic. I'll let him chime in here in case I am recalling his comments incorrectly from when he was taking his second stab at adding a `Transition` component.

**Comment by moaxaca** [comment]
@brianespinosa 
That sounds good, I am looking forward to hearing from him. One that I discovered while implementing this the lack of CSS3 transitions against auto-calculated values. Here is a document describing the problem and some workarounds. I should note this only applies to the container of the accordion, not the content that's being animated. 

https://css-tricks.com/using-css-transitions-auto-dimensions/

I will explore the current implementation of Transition and see if there's a graceful solution.

**Comment by GCrispino** [comment]
Good to know that there’s someone working on this. I’m new to the Semantic UI codebase, but I’m interested in contributing to this enhancement, if needed

**Comment by moaxaca** [comment]
@GCrispino Thanks, were currently waiting for the maintainers to engage.

**Comment by GCrispino** [comment]
@moaxaca Ok cool!

**Comment by tayupov** [comment]
What's the status on this?

**Comment by moaxaca** [comment]
@tayupov  need author feedback. @brianespinosa could we get the label "needs author feedback"

**Comment by Whipgit** [comment]
How can we get a follow-up to this?

**Comment by layershifter** [comment]
The right way was described for the implementation [there](https://github.com/Semantic-Org/Semantic-UI-React/pull/2001#issuecomment-326613796).

**Comment by moaxaca** [comment]
@layershifter I will review and take a look at it this weekend.

**Comment by hugomn** [comment]
@moaxaca Why was this closed? Can I help somehow?

**Pull request closed without merging**
