### PR TITLE
fix(Portal): remove non-working `style` prop

### LINKED ISSUE #2886: Portal: recent change breaks in IE11
## Bug Report

A change introduced in #2657 to the portal component causes an error in IE11 when trying to open anything using a portal.

The change: 
https://github.com/Semantic-Org/Semantic-UI-React/blob/500df9ae073dc99b3425fda89fe6b3a3d8f56760/src/addons/Portal/Portal.js#L355

### Steps
Use anything with a portal in IE11 and try to open it.

### Expected Result
Should open the portal.

### Actual Result
Throws the following error:
```
SCRIPT5045: Assignment to read-only properties is not allowed in strict mode
```
Which points to the changed line.

### Version
`semantic-ui-react@0.81.1`

### PR DESCRIPTION
**Pull request by mgandley**
Instead of setting the style property of a dom node (which is a read-only attribute), we set the cssText property instead.

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style for additional documentation.

Even so, most browsers allow setting style directly.  However, doing this in IE causes a crash.

This fixes #2886.

### CODE REVIEW

**Review by layershifter — CHANGES_REQUESTED** [review]
I am not sure, that this fixes something. Try to pass to `style` prop to the Portal.

**Comment by layershifter** [comment]
I also don't understand why actually need to assign something to the `style` there, because we don't use this in Portal.

I think that we can safely drop this line and `style` prop on Portal.

**Comment by mgandley** [comment]
Yeah - I made the faulty assumption that the style prop would be a string, but checking the docs it's an object.  Could probably swap to set style via setAttribute which automatically converts the input value to a string.

That said, if not used, makes more sense to just purge the line of code.

**Comment by layershifter** [comment]
Let's try to remove `style` prop fully as non-working.

**Comment by layershifter** [comment]
You need also remove it in `Portal.d.ts`.

**Review by layershifter — APPROVED** [review]

**Comment by mgandley** [comment]
You beat me by seconds.  🥇

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.81.3`.

**Pull request merged**
