### PR TITLE
breaking(Portal|Popup): replace mouseOver event listener with mouseEnter

### PR DESCRIPTION
**Pull request by dvdzkwsk**
# Breaking Change

Fixes https://github.com/Semantic-Org/Semantic-UI-React/issues/978.

This PR replaces all `mouseOver`-related `<Portal />` events with `mouseEnter` to be consistent with `mouseLeave`. This affects the `<Portal />` component directly, as well as any which implement it, which at this time includes `<Popup />`.

### Upgrade Guide

All related `mouseOver` props should now be `mouseEnter`. This will also impact the logic of these handlers since they are now only called when the element is entered, not (incorrectly) on enter and exit.

**BEFORE**
```jsx
const onMouseOver = () => {
  console.log('Entered (or exited!!) the element in the portal')
}

<Portal onMouseOver={onMouseOver} trigger={<h2>hello</h2>} />
```

**AFTER**
```jsx
const onMouseEnter = () => {
  console.log('Entered the element in the portal')
}

<Portal onMouseEnter={onMouseEnter} trigger={<h2>hello</h2>} />
```

### CODE REVIEW

**Comment by levithomason** [comment]
I know you're a  busy fellow, any progress here @davezuko?  Icon docs are borked without this guy.

**Comment by dvdzkwsk** [comment]
No, perhaps I will take a stab again tonight. There's a failing test or two that I'm absolutely stumped on, but maybe a fresh look will solve it.

**Comment by levithomason** [comment]
Cool, LMK.

**Comment by levithomason** [comment]
Nice, this looks good.  Want to add some breaking change notes as laid out in https://github.com/Semantic-Org/Semantic-UI-React/issues/978#issuecomment-265064306?  Also, the title will then be `breaking(Portal): ...`.

**Comment by dvdzkwsk** [comment]
@levithomason how is this?

**Comment by levithomason** [comment]
Looks great, thanks!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.63.0`.

**Pull request merged**
