### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by brianespinosa**
Updated the main README.md file with a link to the issue regarding compatibility with SUI 2.3

### CODE REVIEW

**Comment by brianespinosa** [comment]
@levithomason @layershifter One of you will have to merge this. I am not authorized to merge.

**Comment by levithomason** [comment]
Thanks!  I'm in the process of moving out of state.  So I'll be distracted for a bit with that.

**Comment by brianespinosa** [comment]
@levithomason good luck!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.79.0`.

**Pull request merged**
