### PR TITLE
fix(Dropdown): fix compatibility with IE

### LINKED ISSUE #1315: Dropdown won't open in IE if openOnFocus is false
### Steps
1. I have a dropdown with search and selection enabled and ```openOnFocus={false}```
2. I open the website in Internet explorer 11
3. I click the dropdown with the mouse

### Expected Result
The dropdown should open when clicked. 

### Actual Result
 I get a javascript error from this row in the code:
```if (options[nextIndex].disabled) return _this.moveSelectionBy(offset, nextIndex);```
saying that ```options[nextIndex]``` is undefined
The dropdown don't open

### Version
0.64.5

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1315.

### CODE REVIEW

**Comment by levithomason** [comment]
@cattermo does this PR resolve your issue?

**Comment by cattermo** [comment]
It works! 

Sorry for the delay, I thought I could npm install the branch from github directly but couldn't get it to work (corporate firewall...). Ended up copypasting the new code right into node_modules which proved working fine for testing purpuse.

**Comment by levithomason** [comment]
Thanks for the testing and report @cattermo.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.4`.

**Pull request merged**
