### PR TITLE
fix(Dropdown): more logic for clearing search

### LINKED ISSUE #1952: Multi-select Dropdown does not clear value after "onAddItem"
### Steps
1. Type a new value into the input field such as "foo"
2. Click "Add foo" to add the new item

### Expected Result
Input field will have a label with value "foo" and current typed value will be empty

### Actual Result
Input field has a label with value "foo" and current typed value is still "foo"

### Version
Breaks on 0.71.3+

Looks like it may have come from this commit: https://github.com/Semantic-Org/Semantic-UI-React/commit/62507c20dc035a35d54e2267f8299c2a18d81525#diff-609214949026e594dbfd98481664c928R705

### Testcase
https://codepen.io/lott/pen/PKjQge

### PR DESCRIPTION
**Pull request by lott-ai**
Fixes #1952.

* fix(Dropdown): clear search if adding item or if selection is only option #1952
* test(Dropdown): add test for clear search if selection is only option

### CODE REVIEW

**Comment by levithomason** [comment]
Heads up, tests are failing due to lint:

```
/home/ubuntu/Semantic-UI-React/src/modules/Dropdown/Dropdown.js
  599:53  error  Extra semicolon  semi
  603:64  error  Extra semicolon  semi
  702:64  error  Extra semicolon  semi
  711:53  error  Extra semicolon  semi
```

You can run `npm run lint:fix` to fix most errors and then push.  Note that you can ignore warnings.

**Comment by rijk** [comment]
Awesome this will be fixed + the extra tests. Great work @ChrisNLott , hope it will be merged soon, this is really bugging us in production as well.

**Comment by levithomason** [comment]
Thanks much @ChrisNLott.  I'll make a release today.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.5`

**Pull request merged**
