### PR TITLE
style(mixed): update typings for usage with UMD

### LINKED ISSUE #1392: index.d.ts file with semanticUIReact
How can I have typed `semanticUIReact` in a TypeScript file? I have tried:

    /// <reference path="../node_modules/semantic-ui-react/index.d.ts" />
    const { Menu } = semanticUIReact

But I get `cannot find name semanticUIReact` error.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1392.

### CODE REVIEW

**Comment by levithomason** [comment]
Agreed on the extra reviewers here. I'm not sure about exporting a single namespace versus individual exports.

**Comment by levithomason** [comment]
Perhaps @czb could test this out as he is requesting it.  @dennari and @asvetliakov are also superb TS users and may have opinions here.

**Comment by layershifter** [comment]
Needs rebase after #1467.

**Comment by levithomason** [comment]
Fixed.

**Comment by layershifter** [comment]
PR was merged, I've need make rebase and actualize this PR.

**Comment by layershifter** [comment]
I want to close this for housekeeping. I don't see there any feedback from users while changes in this PR looks very ugly. I'm glad to see some feedback, possible it can be done more elegant.

**Comment by levithomason** [comment]
Agreed, we can always revisit this but I would like to clean up the open issues and PR's as much as possible.

**Pull request closed without merging**
