### PR TITLE
feat(Progress): Add value option, to just show the value in the bar

### PR DESCRIPTION
**Pull request by UnbrandedTech**
This PR adds ability to pass `value` to `Progress`:

```jsx
  <Progress progress='value' value={35} />
```

### CODE REVIEW

**Comment by UnbrandedTech** [comment]
Hey @layershifter or @levithomason, I think this is good to go. Let me know what you think.
This is what im trying to accomplish btw. I'll deal with the css, but the value inside is what I need.
screen shot 2017-12-14 at 9 32 47 am

**Comment by levithomason** [comment]
Though this is an extension of the SUI Progress settings, I think it makes sense.  If you could add some tests ~~, typings,~~ and docs to this we can merge it.

**Comment by UnbrandedTech** [comment]
I'm not sure why that test it failing....

**Comment by layershifter** [comment]
@levithomason I'm pushed some changes to make this working, however I think that it will be better if we will introduce `Progress.Progress` component and allow to use it as shorthand.

**Comment by UnbrandedTech** [comment]
Any update on this?

**Comment by levithomason** [comment]
This looks good to me.

@layershifter what do you mean about `Progress.Progress`, can you give some shorthand examples?   Maybe we do this in another PR?

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.77.2`

**Pull request merged**
