### PR TITLE
docs(Example): add ShorthandExample and ability to version docs

### PR DESCRIPTION
**Pull request by layershifter**
This PR:
- add ability for versioning the documentation with SUI version
- add dedicated example component for shorthands

-----

### Shorthands

I think that each example should have full and shorthand markup and this code will be more clear for us:

```jsx
<ComponentExample
  title='Icon Group'
  description='Groups can be formatted as icons.'
  examplePath='elements/Button/GroupVariations/ButtonExampleGroupIcon'
/>
<ShorthandExample examplePath='elements/Button/GroupVariations/ButtonExampleGroupIconShorthand' />
```

### CODE REVIEW

**Comment by levithomason** [comment]
I was thinking of publishing multiple versions of the doc site itself.  Something like lodash:

image

How do you envision we'd go about adding version tags to examples/components?  One other idea is to use jsdoc tags.  These would be parsed and added to `docgenInfo.json` by default with the current workflow.

I like the shorthand example idea.  It would be great to figure a way to give us hints as to which components are missing shorthand examples.

Maybe to move this one forward you could update this PR with a couple examples and we can make a determination from there.

**Comment by layershifter** [comment]
@levithomason I like your idea, I think that we will go with it. However, I still think that proposed idea with tags is good for SUI. I will make some updates.

**Comment by layershifter** [comment]
Merge conflicts should be resolved

**Review by layershifter — COMMENTED** [review]
Merge conflict resolved, ready for review

**Comment by layershifter** [comment]
Has merge conflicts

**Comment by layershifter** [comment]
I solved merged conflicts, however I want merge #1981 before this, becuase there will be merge conflicts.

**Comment by levithomason** [comment]
Unblocked, merged #1981

**Comment by layershifter** [comment]
@levithomason I've merged with `master` and updated initial message for clarification. Ready for review.

**Comment by levithomason** [comment]
Looks good, thanks!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.73.0`

**Pull request merged**
