### PR TITLE
style(Form): convert component to stateless

### PR DESCRIPTION
**Pull request by layershifter**
#1367 removed all handlers, so `Form` can be stateless now :smile:

### CODE REVIEW

**Comment by levithomason** [comment]
🎉

**Comment by ak99372** [comment]
What is the actual reason (or change request) to convert it to stateless and how do we handle submit or serialize the form from now on?

**Comment by levithomason** [comment]
Please see the linked PR for before/after code examples for upgrading and more context on why the change.

**Comment by ak99372** [comment]
Thx Levi I didn't see the reference to #1367 .

**Comment by levithomason** [comment]
No worries, let me know if there are any further questions we could have answered.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.1`.

**Pull request merged**
