### PR TITLE
breaking(Statistic): refactor Statistic to use factories, update content props

### PR DESCRIPTION
**Pull request by layershifter**
# Why?

- use our factories
- removes manual `key` generation, #1533
- use `content` instead of custom props
- cleanup docs

-----

### `Statistic.Label`, `Statistic.Value`

| Before | After |
| ------------- | ------------- |
| `<Statistic.Label label='foo' />`  | `<Statistic.Label content='foo' />`  |
| `<Statistic.Label label={<div>foo</div>} />`  | `<Statistic.Label content={<div>foo</div>} />`  |
| `<Statistic.Value value='foo' />`  | `<Statistic.Value content='foo' />`  |
| `<Statistic.Value value={<div>foo</div>} />`  | `<Statistic.Value content={<div>foo</div>} />`  |

#### Before

```jsx
<Statistic
  label={<div>label</div>}
  value={<div>value</div>}
/>
```

#### After

```jsx
<Statistic
  label={{ content: <div>label</div> }}
  value={{ content: <div>value</div> }}
/>
// or
<Statistic
  label={<Statistic.Label>label</Statistic.Label>}
  value={<Statistic.Value>value</Statistic.Value>}
/>
```

#### Before

```jsx
const items = [
  { label: 'foo', value: 'bar' },
  { label: 'baz', value: 'qux' },
]
<Statistic.Group items={items} />
```

#### After

`key` is **required** now.

```jsx
const items = [
  { key: 'foo', label: 'foo', value: 'bar' },
  { key: 'baz', label: 'baz', value: 'qux' },
]
<Statistic.Group items={items} />
```

### CODE REVIEW

**Comment by levithomason** [comment]
One question, why is this syntax not supported anymore?

```jsx
<Statistic
  label={<div>label</div>}
  value={<div>value</div>}
/>
```

Factories support passing elements.

**Comment by layershifter** [comment]
`Statistic` now uses factories to create `Statistic.Label` and `Statistic.Value`, so this example will produce following markup:
```html
<div class="ui statistic">
  <div>value</div>
  <div>label</div>
</div>
```

It will don't contain valid `className`s.

**Comment by levithomason** [comment]
Heads up, in the future, I'd like to make factories ensure required classNames are present 👍 Thanks for the work here!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.75.0`

**Pull request merged**
