### PR TITLE
docs(readme): add amazon publishing to built with

### PR DESCRIPTION
**Pull request by austinfox**

### CODE REVIEW

**Comment by levithomason** [comment]
This is superb!  I hoist well-known companies to the top of the list.  I've taken a snippet from the apub.com landing page for the description.  It should also generate a little more SEO hits.

Once you verify the changes are OK to publicize, I'll merge.

**Comment by austinfox** [comment]
Thanks for the changes, LGTM :)
I'll post in this issue (https://github.com/Semantic-Org/Semantic-UI-React/issues/1604) in a bit with an internal screen shot of our app. We have been migrating from stock semantic-ui with custom react wrappers to semantic-ui-react, and it has been an absolute pleasure to use. I'm so glad to be rid of jquery, thanks so much for all your work. I'll try to be an active contributor and make this package even better.

**Comment by levithomason** [comment]
Very cool, we're looking for a few hands to join!  Will wait for the screenshot.

**Comment by levithomason** [comment]
Merging for now.  Would be great to get some screenshots on this issue and update the README to link here as well.

**Pull request merged**
