### PR TITLE
fix(TextArea): Make TextArea's height shrink (#3418)

### PR DESCRIPTION
**Pull request by codrex**
This fixes the issue reported [here](https://github.com/Semantic-Org/Semantic-UI-React/issues/3418)

## Before
bug

## After
fix

### CODE REVIEW

**Comment by layershifter** [comment]
@codrex thank you for the PR, checked in Chrome.

### Zoom 100%

Works fine.

zoom-100

### Zoom 90%

Appears a scroll bar.

zoom-90

**Comment by codrex** [comment]
@layershifter You welcome. I will check this out.

**Comment by codrex** [comment]
fix2

@layershifter updates have been made to the PR. A scroll bar still appears and disappears at a given size. Going through the current implementation I discovered the same behavior.

**Comment by layershifter** [comment]
@codrex thank you for your effort there, I really appreciate it 👍

However, I opened #3465 with the detailed description why I want to do that changes. Sorry for the late response, I wanted to hear the opinion from the team that uses SUIR very long time.

**Pull request closed without merging**
