### PR TITLE
chore(mixed): renamed unsafe lifecycle methods

### LINKED ISSUE #3741: Warnings about lifecycle methods
### Steps
Use `Dropdown` with `semantic-ui-react@0.87.3` and `react@16.9.0-rc.0`
Open your console to see the warnings

### Expected Result
No warnings should appear

### Actual Result
```
      Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

      * Move code with side effects to componentDidMount, and set initial state in the constructor.
      * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

      Please update the following components: Dropdown
```

### Version
0.87.3

### Testcase
https://codesandbox.io/s/semantic-ui-react-y6s9z?fontsize=14

### PR DESCRIPTION
**Pull request by jmyrland**
Executed via `npx react-codemod rename-unsafe-lifecycles --parser babel`
Disabled lint issues for updated lines.

The changes should mitigate the "Unsafe lifecycle" warnings.

Closes #3741
Related to #2732

### CODE REVIEW

**Comment by jmyrland** [comment]
Additional info: only the `src` folder has been affected by this change.

Also, most of the files were skipped (asuming they did not need a change).

**Comment by layershifter** [comment]
@jmyrland thank you for taking this ❤️

I updated PR with `react` package bump to ensure that we don't have any issues, but CI failed on two tests. Trying to understand why 🤔

**Comment by jmyrland** [comment]
Nice @layershifter 👍 Kudos for all the effort in making condributions "newb-friendly" 😁 Really easy to get up and running with the project & ready to contribute 👌

As for the failing tests - I'm not sure whats causing this, but I see you "fixed" it by disabling some of the tests.

Let me know if you need anything else from my end 👍

**Review by layershifter — APPROVED** [review]

**Comment by layershifter** [comment]
> Nice @layershifter 👍 Kudos for all the effort in making condributions "newb-friendly" 😁 Really easy to get up and running with the project & ready to contribute 👌

😍 

> As for the failing tests - I'm not sure whats causing this, but I see you "fixed" it by disabling some of the tests.

Yea, I don't have any idea why they fails

**Pull request merged**
