### PR TITLE
feat(Card): add centered prop to Card.Group

### LINKED ISSUE #2453: Card: add centered prop to Card.Group
Add centered prop to Card.Group

### PR DESCRIPTION
**Pull request by sudheerDev**
Add centered prop for card groups 

Closes #2453

### CODE REVIEW

**Comment by layershifter** [comment]
@sudheerDev an example of usage will be awesome 👍

**Comment by sudheerDev** [comment]
@layershifter added an example. Can you please check and tell me why the coverage in visibility.js came down?

**Comment by layershifter** [comment]
@sudheerDev Thanks, awesome work 👍 About coverage: just ignore it there 😄

**Comment by sudheerDev** [comment]
@layershifter No problem. Glad I could help. Thanks for the fixes :)

**Comment by layershifter** [comment]
Merged, thanks again 👍

**Comment by levithomason** [comment]
Released in `semantic-ui-react@v0.78.0`.

**Pull request merged**
