### PR TITLE
Use consistent, specific imports

### PR DESCRIPTION
**Pull request by marshallswain**
This updates the entire package with consistent imports.  Updating the imports to be file-specific instead of using the folder shorthand ensures compatibility with all module loaders.

### CODE REVIEW

**Comment by levithomason** [comment]
Initially, I'm not in favor of such a change.  Although, I'd be curious to hear the motivation for this.
***
FWIW, there are also some errors in the updates, such as `TextArea/index.js`:
```js
export default from './TextArea/TextArea'
```

`./TextArea` is a JS file, so there is no extra directory here.

**Comment by levithomason** [comment]
It would also appear we have neither linting nor tests around the index files :)

**Comment by marshallswain** [comment]
The motivation behind this is to allow the package to load in browser-based module loaders like StealJS, which is based on SystemJS.  I figured making a PR is the best solution to making it work everywhere. And while the loaders do allow you to create a configuration map of the files, I was hoping to avoid doing that.  I'm also hoping to avoid having to switch back to Webpack to use the package.

If I change the imports to go through the `index.js` files and audit/clean up the mistakes, are you open to allowing the change?  Thank you!

**Comment by marshallswain** [comment]
I've cleaned up those mistakes and switched to using the `index.js` files.  Please let me know if there's anything I can do that would help you feel more comfortable merging this.

**Comment by levithomason** [comment]
I certainly want maximum interop for the lib.  My ignorance is exposed regarding browser module loaders.  I'll take a look at those and review this PR in light of that.  Thanks for the work and extra explanation here.

**Comment by levithomason** [comment]
Note for the future.  PRs opened from a branch on your fork will allow myself and the collaborators here to push updates to it.  Though, this is not possible against your master branch.  This is handy for fixing conflicts, lint issues, and tests, if needed.

No need to reopen a new PR, just a note for the future 👍 Thanks again!

**Comment by marshallswain** [comment]
This is the issue I'm trying to resolve.  When I try to use the CommonJS or ES6 formats of the module, I get the errors in this screenshot.  I'll file an issue with StealJS, too.

screen shot 2017-01-25 at 9 03 17 am

**Comment by matthewp** [comment]
Hi, I'm the maintainer of StealJS.  As I understand from this discussion, the package.json main of `dist/commonjs/index.js` is not meant to be loaded in a browser. Given that, you could fix this by including a `browser` configuration that points to the umd build: `"browser": "dist/umd/semantic-ui-react.min.js"` should do it.

**Comment by levithomason** [comment]
I've previously implemented the `browser` field, https://github.com/Semantic-Org/Semantic-UI-React/pull/702, however, this immediately broke several users' webpack builds, #703.  When creating a bundle with Webpack, requiring `semantic-ui-react` results in the UMD build being bundled, which is of course not what you want when creating a bundle on the server.  Hence, it was quickly reverted, #704.

I'd like to get this going, though, as it stands it seems there is either not full community agreement on the [browser field spec](https://github.com/defunctzombie/package-browser-field-spec), or, I am misunderstanding some part of it.

**Comment by matthewp** [comment]
Ah, I follow, webpack gives preference to the browser field. So we need a field that webpack will ignore.  We actually have one for steal: `"steal": { "main": "path/to/browser/main.js" }` but I can understand if you don't want to implement a loader-specific configuration. I wish there was an accepted field that webpack left alone.

**Comment by levithomason** [comment]
Indeed, I'll take a look around and see if anyone has solved this yet.  As far as webpack's implementation is concerned, the `browser` field is for isomorphic versions of your modules that are bundler agnostic.

Without a clear spec nor solution at hand, I'm going to close this for now.  It is not pretty, but as a workaround @marshallswain, you can import the full file path:

```js
import Container from 'semantic-ui-react/dist/commonjs/elements/Container'
```

I'd also suggest discussing ES module support with @matthewp.  We provide an `es` build which can take advantage of tree shaking (i.e. Rollup, Webpack 2, etc).

**Comment by marshallswain** [comment]
Thanks @levithomason.  I'll submit a PR for the mixed module syntax in the debug.js file.  That's preventing me from being able to use it as you suggested above.

**Pull request closed without merging**
