### PR TITLE
feat(Grid): allow multiple values for `reversed` prop

### LINKED ISSUE #2222: Grid: allow multiple values for `reversed` prop
### Steps
Trying to create a grid whose columns are reversed on Mobile **and** Tablet.
I tried:
```
<Grid reversed="computer tablet">
// or
<Grid reversed="computer,tablet">
// or
<Grid reversed="computer|tablet">
// or
<Grid reversed={["computer","tablet"]}>
```

### Expected Result
Same behavior as in Semantic UI: https://codepen.io/dhilgarth/pen/Naezay

### Actual Result
Error message:

> Warning: Failed prop type: Invalid prop reversed of value computer,tablet supplied to GridRow, expected one of ["computer","computer vertically","mobile","mobile vertically","tablet","tablet vertically"].

### Version
0.75.1

### Testcase
https://codesandbox.io/s/w0n3wp9j48

[See also my question on SO](https://stackoverflow.com/q/46807674/572644)

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2222.

### CODE REVIEW

**Comment by levithomason** [comment]
Awesome, thanks!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.76.0`

**Comment by Maxhodges** [comment]
what's the syntax for multiple values in reversed? seems undocumented

**Comment by ghost** [comment]
@layershifter Is there any chance that some side effect of this change is the source of my compile errors when moving from 0.75.1 to 0.76.0?

````
./node_modules/semantic-ui-react/dist/es/collections/Grid/GridRow.js
26:128-143 '../../lib' does not contain an export named 'useMultipleProp'.
````
If I go back to 0.75.1 the issue goes away.

**Comment by layershifter** [comment]
Please open new issue an fully describe your problem there.

**Pull request merged**
