### PR TITLE
breaking(TextArea): remove `autoHeight` prop

### LINKED ISSUE #3418: TextArea with autoHeight doesn't shrink when lines deleted
### Step

1. Input multiple lines in a TextArea with `autoHeight`  // → TextArea's height grows to fit the lines
2. Delete some lines.

### Expected Result

TextArea's height shrinks to fit the remaining lines.

### Actual Result

TextArea's height doesn't change on deleting.

feb-07-2019 18-40-45

### Version
0.85.0
Does not occcur in 0.84.0.

### Testcase
**https://codesandbox.io/s/qzn3nzwr1j 0.85.0**
https://codesandbox.io/s/104r4oy993 0.84.0 (correct)

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #3418.

# BREAKING CHANGES

This PR removes the `autoHeight` prop from the `TextArea` component.

### Motivation

We had numerous issues with `TextArea` component and `autoHeight` prop:
- #3418
- #3343
- #2173
- #1925
- #1843
- #1478
- #1405
- https://github.com/Semantic-Org/Semantic-UI-React/issues/982#issuecomment-266915712

I had a conversation with team from Ukraine that continuously uses SUIR and they said that `autoHeight` is buggy and they are using [`react-textarea-autosize`](https://www.npmjs.com/package/react-textarea-autosize), too 😼 

So, as @levithomason originally proposed I will suggest to use [`react-textarea-autosize`](https://www.npmjs.com/package/react-textarea-autosize):
>I would encourage users to use that module if it suits their needs. SUI requires no special classNames nor markup to style the `textarea` when used in a `Form`, so it will work OOTB.

### Before

```jsx
import { Form, TextArea } from 'semantic-ui-react'

//

<Form.TextArea autoHeight />
<TextArea autoHeight />
```

### After

```jsx
import { Form, TextArea } from 'semantic-ui-react'
import TextareaAutosize from 'react-textarea-autosize'

//

<Form.TextArea control={TextareaAutosize} />
<TextareaAutosize  />
```

I also created a Codesandbox example with how-tos, https://codesandbox.io/s/1v67906ll4. It will be available on the [Prototypes](https://react.semantic-ui.com/prototypes) page after the next release, but you can start to migrate right now.

### CODE REVIEW

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.86.0`.

**Comment by TristanPouliquen** [comment]
@layershifter  Hi, I'm trying to migrate to your new implementation with TextAreaAutosize to work with forms in a Semantic Accordion.

However, I can't seem to get the textarea value in the onChange function. I looked at your Sandbox and I also get `undefined` when I log `data.value`in your example (how the value is kept in memory I do not know as you also do `value={this.state.value}` and the value is also undefined in the state I get from my console.log.

Do you have any idea as to why ? Thanks in advance !

**Comment by layershifter** [comment]
> However, I can't seem to get the textarea value in the onChange function. 

You should use:

```jsx
onChange={e => this.setState({ value: e.target.value })}
```

I've update CodeSandbox to reflect this 👍

**Comment by TristanPouliquen** [comment]
Thanks for your swift answer ! It works as a charm :+1:

**Pull request merged**
