### PR TITLE
feat(Input): expose select() method from ref

### PR DESCRIPTION
**Pull request by kierenj**
(Just as "focus" is currently)

### CODE REVIEW

**Comment by levithomason** [comment]
Great, let's also add a test for this.  You can reference the focus test as an example:

https://github.com/Semantic-Org/Semantic-UI-React/blob/43793ae59df9504131d1c9af4762a75321aa3ccc/test/specs/elements/Input/Input-test.js#L145

**Comment by levithomason** [comment]
Merged master and added a test.  This is ready for merge once CI passes.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.82.0`.

**Comment by kierenj** [comment]
@levithomason thanks for seeing this one through properly - I had intended to get to the test but other things got in the way. Much appreciated :+1:

**Pull request merged**
