### PR TITLE
Update Menu to v1 API

### PR DESCRIPTION
**Pull request by awei01**
Semantic-UI allows menu items with the class `header` to be `<div>`. Change behavior to allow `header` property that will then render a `<div>`. If MenuItem has `header` and `href` prop, then, render `<a>` tag.

### CODE REVIEW

**Comment by levithomason** [comment]
Thanks for the PR.  The `Menu` component is scheduled to be updated to our v1 API pattern, see #269. The concern I have is that if I release this `header` update, it will be immediately over turned by the Menu API update.

The [CONTRIBUTING.md](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md) guide details how to go about designing a component API.  The [Spec out the API](https://github.com/TechnologyAdvice/stardust/blob/master/CONTRIBUTING.md#spec-out-the-api) section is of primary importance here.  There are also a number of great example PRs to reference linked in #269.

Would you be interested in updating the Menu component's API entirely?

**Comment by awei01** [comment]
Not sure what your timeline is, but I can certainly contribute. I'll start with specs. Closing this PR for now.

**Comment by levithomason** [comment]
You'll see in the contributing guide that we'd love to have the spec right here in the PR.  Feel free to re-open and use the PR description or comments for the spec!  ;)

**Comment by awei01** [comment]
Ok this is a huge component... I'll give it a whirl, but please forgive any glaring oversights.

**Comment by levithomason** [comment]
If it seems like a bit much to bite off at once, I can whip up the first spec and we can iterate from there.  LMK.

**Comment by awei01** [comment]
# Menu API Proposal

This is really just to get the ball rolling... 

```
<Menu>
    ...
</Menu>
```

```
<div class="ui menu">
    ...
</div>
```

**Comment by levithomason** [comment]
## Types

All the Menu Types will follow this pattern, so we can just spec the one and extrapolate it to all Types: `secondary` `pointing` `tabular` `text` `vertical` `pagination`.

``` jsx
<Menu secondary>
  ...
</Menu>
```

``` html
<div class="ui secondary  menu">
  ...
</div>
```

**Comment by levithomason** [comment]
We should address #142 in this PR as well.

**Comment by awei01** [comment]
@levithomason Sorry, but I won't be able to contribute as much time as I had hoped.

**Comment by levithomason** [comment]
OK, thanks for the note.  I'll close this PR for now.  Let me know if you decide to pick it back up later.

**Pull request closed without merging**
