### PR TITLE
feat(Embed): add iframe shorthand

### LINKED ISSUE #1804: Embed: add shorthand for iframe
✔ BUGS → This form is required:
When embedding a youtube video the fullscreen option is disabled. This should be a property for the Embed component.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1804.

### CODE REVIEW

**Comment by layershifter** [comment]
@levithomason There is single failing test:

> iframe shorthand prop (common)
> ✖ renders a iframe from elements

I can't fix it, looks like a problem with default value `src`, but nothing changes if I define it in `shorthandDefaultProps`. BTW, we can simply pick the `strictAssert` feature from #1795.

**Comment by layershifter** [comment]
Requires #1845.

**Review by layershifter — COMMENTED** [review]
Unblocked, ready for review 👍

**Comment by levithomason** [comment]
👍

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.3`

**Pull request merged**
