### PR TITLE
style(typings): export all props interfaces

### LINKED ISSUE #1456: TypeScript definition errors in v0.67.1
Greetings,

The latest version introduces several TypeScript errors.

**a) Internal errors:**
```
node_modules\semantic-ui-react\dist\commonjs\collections\Table\TableFooter.d.ts
(2,10): error TS2305: Module '"node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableHeader"'
has no exported member 'TableHeaderProps'.

node_modules\semantic-ui-react\dist\commonjs\collections\Table\TableHeaderCell.d.ts
(2,10): error TS2305: Module '"node_modules/semantic-ui-react/dist/commonjs/collections/Table/TableCell"'
has no exported member 'TableCellProps'.
```

**b) Props interfaces that are no longer exported:**
```
Module '"node_modules/semantic-ui-react/index"' has no exported member 'LabelProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'InputProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'IconProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'IconGroupProps'.
Module '"node_modules/semantic-ui-react/index"' has no exported member 'ButtonProps'.
etc.
```

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1456.

### CODE REVIEW

**Comment by layershifter** [comment]
Almost done there, I want to check it with my typescript pet-project in evening.

**Comment by layershifter** [comment]
@mihai-dinculescu @rokoroku @DanHarman I will be glad to hear your feebback there.

**Comment by rokoroku** [comment]
Looks good 👍

**Comment by mihai-dinculescu** [comment]
I am now able to do 

`import { IconProps } from 'semantic-ui-react';`

but I'm not able to do 

`import { Icon } from 'semantic-ui-react';`

Same goes for the other components.

Thou I'm not sure that I have taken the right approach in testing. I have built the branch and copied `dist` and `index.d.ts` to my project's `node_modules/semantic-ui-react` folder.

**Comment by layershifter** [comment]
@mihai-dinculescu I've added commit that updates exports again. Can you check?

I've tested with compiler in my project, project was built successfully without errors.

**Comment by levithomason** [comment]
Changes look good, will merge once the fixes are confirmed.

**Comment by mihai-dinculescu** [comment]
@layershifter it works great, thank you!

**Comment by mihai-dinculescu** [comment]
@layershifter the TypeScript part works well but there's a React warning now.

`Warning: Invalid argument supplied to oneOfType, expected an instance of array.`

It seems to come out of **ButtonOr.js:36**

`text: PropTypes.oneOfType(PropTypes.number, PropTypes.string)`

`[ ]` is missing.

**Comment by layershifter** [comment]
This was fixed in #1477.

**Comment by mihai-dinculescu** [comment]
@layershifter Then all is good!

**Comment by layershifter** [comment]
@levithomason Seems we can merge this :+1:

**Comment by Jameskmonger** [comment]
Thanks for this @layershifter, it is currently blocking me.

**Comment by levithomason** [comment]
Very appreciative to everyone who tested and reported back here!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.2`.

**Pull request merged**
