### PR TITLE
docs(Icon): fix similar icon search

### LINKED ISSUE #2193: docs(Icon): "Show similar" does not filter at all on the deployed docs site
### Steps
Go to https://react.semantic-ui.com/elements/icon, have the "Show similar" checked (it is by default), and search for "home".

#### Environment
Have tested in Firefox 56.0.1 and Chrome 61.0.3163.100.

### Expected Result
The icon "home" will show up (and maybe some related icons)

### Actual Result
No filtering happens at all, for no search strings. It does however filter when **not** having the "Show similar" checked. 

It does work on the local build, however. I.e. when running ```yarn start``` in the source directory and accessing it from localhost, the "Show similar" functionality works.

### PR DESCRIPTION
**Pull request by patrikmolsson**
Fixes #2193.

Addresses the issue described in https://github.com/Semantic-Org/Semantic-UI-React/issues/2193

Merely tested on fork's deployed site: https://patrikmolsson.github.io/Semantic-UI-React/.

### CODE REVIEW

**Review by layershifter — APPROVED** [review]
@patrickgaskill Awesome work :+1: Thanks for finishing it

**Comment by patrikmolsson** [comment]
@layershifter Of course :) Just a question, how come the tests were failing?

**Comment by layershifter** [comment]
There is a strange bug with one of `Modal` tests, I can't reproduce it locally. Sometime it fails, sometime - no :thinking:

**Comment by patrikmolsson** [comment]
@layershifter Is this the new Modal test? From 0.75?

**Comment by layershifter** [comment]
Nope, it fails periodically from `0.74.x` as I remember:

```
FAILED TESTS:
  Modal
    dimmer
      false
        ✖ does not add any dimmer classes to the body
          HeadlessChrome 0.0.0 (Linux 0.0.0)
          AssertionError: document.body should not have class "dimmable", but it has class="dimmable dimmed": expected true to equal false
              at test/utils/assertBodyClasses.js:22:0
              at Array.forEach (<anonymous>)
              at assertBodyClasses (test/utils/assertBodyClasses.js:17:0
              at Context.<anonymous> (test/specs/modules/Modal/Modal-test.js:280:0
```

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.76.0`

**Pull request merged**
