### PR TITLE
fix(Modal): do not close when mouse click was occurred inside

### PR DESCRIPTION
**Pull request by joergbaier**
The default modal closes when:

1. When a click starts in the modal but ends in the dimmer
2. When a click starts in the dimmer but ends in the modal

This can be reproduced in the first example
https://react.semantic-ui.com/modules/modal/

This change will only close the Modal if the click starts and ends in the dimmer.

### CODE REVIEW

**Comment by joergbaier** [comment]
It looks like https://github.com/Semantic-Org/Semantic-UI-React/pull/3575 could use the same change as well.

**Comment by mihai-dinculescu** [comment]
I'm not sure if changing the tests from `domEvent.click` to `domEvent.mouseDown` and `domEvent.mouseUp` is the right aproach. This will not hit the `onClick` handlers and will act differently from reality. I believe that my aproach from https://github.com/Semantic-Org/Semantic-UI-React/pull/3575 to update `domEvent.click` to also fire `mousedown` and `mouseup` is more resilient.

**Comment by joergbaier** [comment]
@mihai-dinculescu I will update this PR to match yours tomorrow.

**Comment by fraynn** [comment]
Thanks for fixing this issue. Do you have any idea on when we can expect this fix to be pushed to npm ?

**Comment by layershifter** [comment]
I think that we will finally make a release on this week 🎉

**Pull request merged**
