### PR TITLE
feat(Table): add `headerRows` to allow to render multiple headers

### PR DESCRIPTION
**Pull request by abaschen**
Same behavior as renderBodyRow with tableData but for the Headers. Necessary when having more than one line in headers.
If headerRow is set then renderHeaderRow and headerData are ignored.

If accepted, maybe do the same for footer?

### CODE REVIEW

**Comment by layershifter** [comment]
https://codesandbox.io/s/wym08vp8zl?module=/example.js

Can you check this CodeSandbox. Does it satisfiy all of your needs? 🐱

**Comment by abaschen** [comment]
Indeed!! I was currently checking and about to commit tests and changes etc... but with this yes it's perfect!

**Comment by abaschen** [comment]
Oops no I've commented too fast. It doesn't satisfy it. how can you have more than one row with rowSpan and so on?

**Comment by layershifter** [comment]
Can you please provide example markup in HTML for it?

**Comment by layershifter** [comment]
Do you mean something like this?
https://codesandbox.io/s/v0344yp7n7

**Comment by abaschen** [comment]
Yes like this but with shorthands

**Comment by layershifter** [comment]
@TecHunter please check changes, going to merge after your confirmation 👍

**Comment by abaschen** [comment]
Okay for me. 

Maybe do the same for footer?

**Comment by layershifter** [comment]
@TecHunter let's do 👍 We can add it in a separate PR

**Pull request merged**
