### PR TITLE
docs(examples): add dependency for babel-plugin-lodash

### LINKED ISSUE #1701: Failed to build webpack2 example
### Steps
Cloned the repository, then ran the following:
npm install
npm run build

### Expected Result
No errors

### Actual Result
Many errors; see attached log file also.
````
PS E:\apps-node\Semantic-UI-React\examples\webpack2> npm run build

> semantic-ui-react-example-webpack2@1.0.0 build E:\apps-node\Semantic-UI-React\examples\webpack2
> webpack

Hash: 8e1be9e74e54b6dc797e
Version: webpack 2.6.0
Time: 281ms
 Asset     Size  Chunks             Chunk Names
app.js  4.54 kB       0  [emitted]  app
   [0] ./src/main.js 1.91 kB {0} [built] [failed] [1 error]

ERROR in ./src/main.js
Module build failed: Error: Plugin 0 specified in "E:\\apps-node\\Semantic-UI-React\\examples\\webpack2\\.babelrc" provided an invalid property of "__wrapped__"
    at Plugin.init (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (E:\apps-node\Semantic-UI-React\examples\webpack2\node_modules\babel-loader\lib\index.js:163:20)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! semantic-ui-react-example-webpack2@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the semantic-ui-react-example-webpack2@1.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui-react-example-webpack2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui-react-example-webpack2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui-react-example-webpack2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\msaro_000\AppData\Roaming\npm-cache\_logs\2017-05-23T14_50_17_089Z-debug.log
PS E:\apps-node\Semantic-UI-React\examples\webpack2>
````
### Version
Windows 10
Node version 7.10.0
npm version 4.2.0

[webpack2 example](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/examples/webpack2)

[2017-05-23T14_50_17_089Z-debug.txt](https://github.com/Semantic-Org/Semantic-UI-React/files/1022586/2017-05-23T14_50_17_089Z-debug.txt)

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1701.

- adds `babel-plugin-lodash` to deps;
- updates all deps;
- splits `analize` to dedicated scripts.

### CODE REVIEW

**Comment by levithomason** [comment]
Fixed a typo, will merge on pass.

**Comment by layershifter** [comment]
@levithomason Seems that you forgot to merge this :smile:

**Comment by levithomason** [comment]
Since this is just a doc update, I'll push it right now.  Thanks for the ping!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.70.0`

**Pull request merged**
