### PR TITLE
fix(TextArea): use onInput for updating height for IE compatibility

### LINKED ISSUE #1925: IE: TextArea: wrong autoHeight counting
Based on https://github.com/Semantic-Org/Semantic-UI-React/issues/1843 which was closed. Unfortunately the very last commit contains an issue in IE browsers

**steps 1:**
copy a long text
paste using context menu

**steps 2:**
make text area to grow some height
select all text in it
using context menu, click 'delete' or 'cut'

**Expected:**
textarea is resized properly in both steps1 and steps2

**Actual:**
the height is not changed

### PR DESCRIPTION
**Pull request by nickpedersen**
Fixes #1925 

This is my first PR, apologies if there are any mistakes.
Added an onInput method to the TextArea component, copying the onChange pattern. Added a test for the onInput method.

Tested in IE11 and the requested behaviour (cutting and pasting) correctly resizes the TextArea.

### CODE REVIEW

**Comment by levithomason** [comment]
One minor conflict here, could you take a look?

**Comment by levithomason** [comment]
@nickpedersen / @layershifter I've rebased, fixed conflicts, and cleaned up typings.  I think this is good to go.  Can you take a look and confirm?

**Comment by layershifter** [comment]
I've removed useless export, now tests are passing. I don't have IE at now, so I can't test. 

@nickpedersen can you take a look?

**Comment by nickpedersen** [comment]
Just tested, can confirm it's working in IE11. Appreciate the help on this PR @layershifter and @levithomason

**Comment by levithomason** [comment]
Thanks guys!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.73.0`

**Pull request merged**
