### PR TITLE
feat(MenuItem): Add missing MenuItem `disabled` prop 

### PR DESCRIPTION
**Pull request by kamdz**
as requested in #1363

### CODE REVIEW

**Comment by levithomason** [comment]
❤️  Fantastic!  Will merge on pass.

**Comment by levithomason** [comment]
Whoops, almost forgot, we need to update the typings as well.  They are in the `index.d.ts` file in the same directory.

**Comment by kamdz** [comment]
done :)

**Comment by levithomason** [comment]
Superb, merge coming for real this time :)

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.66.0`.

**Pull request merged**
