### PR TITLE
feat(Shape): add component

### LINKED ISSUE #196: <Shape /> Component
http://semantic-ui.com/modules/shape.html

### PR DESCRIPTION
**Pull request by layershifter**
# WIP

Fixes #196.

### CODE REVIEW

**Comment by madwill** [comment]
How is this going ? Can we do something to help ?  Help pass the test or something else ?

**Comment by layershifter** [comment]
Without progress as you can see, I have less time now while there are PRs with more priority. Help there is much appreciated.

**Comment by madwill** [comment]
Completely understand, i'll have a closer look and see. Thank you very much for your time.

**Comment by sukeshlaghate** [comment]
Any news on Shape component? If it gets added, would be highly appreciated!

**Comment by levithomason** [comment]
Please feel free to hop in!  Fork the repo, pull the branch and submit a PR to finish this one up.  That would be a huge help 😃

**Comment by layershifter** [comment]
Closing due inactive, feel free to pick up it!

**Pull request closed without merging**
